### ISSUE TITLE
Mangacan

### ISSUE THREAD

**Issue by Reoldyk** [ABPindo/indonesianadblockrules#10]
tolong ditambahkan filter ini.

www.mangacanblog.com###popup
![baca manga komik naruto-one piece-bleach-fairy tail-hunter x hunter-conan indo-mangacan 2016-05-21 09-00-15](https://cloud.githubusercontent.com/assets/4547317/15445813/85407d24-1f32-11e6-9afc-d8ba2b635990.png)

**Comment by gmarcher** [comment]
Dibuat filter pribadi saja, kalau self promotion tidak perlu dihide/block

**Comment by Reoldyk** [comment]
wokeh.

**Comment by Reoldyk** [comment]
kalo mau usul filter tapi untuk adblocker tertentu saja bisa gak?
aku mau usul filter ini
ganool.ph##script:contains(eval(function(p,a,c,k,e,d))

ini hanya bisa berfungsi untuk adblocker Ublock Origin saja,
filter ini untuk memblok iklan ketika menekan link download di halaman ganool, jadi gak akan ada popup ketika link download di tekan.
