### ISSUE TITLE
https://m.kaskus.co.id/home

### ISSUE THREAD

**Issue by rokokkopi** [ABPindo/indonesianadblockrules#108]
Di mobile/smartphone nongol nih gambar iklannya
*biasanya nongol di post yang ada gambar2 

`impulse.forkcdn.com/pub/kaskus/kaskus/generic.js`

**Comment by gmarcher** [comment]
Tolong dilengkapi screenshot dan link pas kedapatan iklannya

**Comment by rokokkopi** [comment]
![Screenshot_2019-08-30-19-48-10-275_com android chrome](https://user-images.githubusercontent.com/48227852/64025969-0c9a8000-cb68-11e9-8a31-c6a48219fb73.png)
![Screenshot_2019-08-30-19-48-21-368_com android chrome](https://user-images.githubusercontent.com/48227852/64025970-0c9a8000-cb68-11e9-81dc-b17e197d78fc.png)

`adnet.forkcdn.com/...`

prikitiew video https://streamable.com/e64e8

**Comment by rokokkopi** [comment]
forkcdn ini kayaknya semacam traffic exchange ads kayak mgid gitu, heran kok gak di blok global di easylist yah.

di kaskus gak selalu nongol, tapi jam/interval tertentu nongol, dan pasti nongol nya diantara ato diapit gambar. kalo post text semua gak bakal ada.

**Comment by gmarcher** [comment]
minta tolong usul filternya gimana? soalnya saya tidak nemu

**Comment by rokokkopi** [comment]
Waduh saya gak paham masalah gini, di mobile gak ngerti troubleshootingnya, kadang nongol kadang gak.

sepertinya sumbernya
`https://impulse.forkcdn.com/pub/kaskus/kaskus/generic.js`

ni ada prikitiew lagi https://streamable.com/jzk6n
nongol pas di artkel "Meski Dianggap Buruk, 5 Film Adaptasi Video Game Layak Kalian Tonton"

**Comment by Hernandy** [comment]
Sudah hilang, bisa di closed.

Sekian dan terima kasih sayang.
