### ISSUE TITLE
safelink ads/boost timer

### ISSUE THREAD

**Issue by WaferNabati** [ABPindo/indonesianadblockrules#116]
request boost countdown

https://wadooo.com/g/QpvRF095iS
https://liputannubi.net/g/QpvRF095iS
https://pantauterus.me/g/QpvRF095iS
https://gotravelgo.space/g/QpvRF095iS
https://bercara.com/kc8wLuEh51J
http://semawur.com/vHiX
http://in11.site/v7CuUpYM

**Comment by 3xploiton3** [comment]
coba pakai addon universal bypasser
atau script adsbypasser
https://adsbypasser.github.io/configure.html

**Comment by WaferNabati** [comment]
udah pake universal bypass 
itu domain punya adsafelink 4 link teratas blom tersuport di universal bypass 
karena tiap hari selalu ganti" domain terus
adsbypasser udah ga update lg

**Comment by 3xploiton3** [comment]
recaptcha setau saya tidak bisa di bypass

**Comment by WaferNabati** [comment]
@3xploiton3 ga paham klo itu tp pke universal bypass bnyak situs yg pake recaptcha langsung kebypass contoh : 
https://fc.lc/YvMVa
http://exe.io/kd9ot7h5
http://g.ceklink.co/lkrFBW3
dan masih bnyak lagi lainya lupa
dan yg bikin bagus dr pada bypass lainya ada fitur crowd bypassnya

**Comment by 3xploiton3** [comment]
Saya coba bisa pakai universal bypass, coba update addonnya atau clear cache cookies

**Comment by WaferNabati** [comment]
maksudnya bisa link yg mana gan ?

**Comment by 3xploiton3** [comment]
https://wadooo.com/g/QpvRF095iS

**Comment by WaferNabati** [comment]
iya itu gw yg request kemaren 3 domain yg dibawahnya kagak bisa
