### ISSUE TITLE
ganool

### ISSUE THREAD

**Issue by p1nkyy** [ABPindo/indonesianadblockrules#12]
Iklan disisipkan entah di mana di situs, sehingga kalo klik button manapun pasti muncul tab baru berisi iklan. Banyak situs lain yang tdk berbahasa Indonesia juga ada iklan model gini, kalau rules-nya bisa global lebih baik lagi. Thanks sebelumnya

**Comment by heradhis** [comment]
Pakai contoh tautan akan lebih membantu.

**Comment by p1nkyy** [comment]
Thank you! Entah update atau filter apa, tapi yang jelas sekarang ganool sudah gak annoying lagi :grinning:
