### ISSUE TITLE
http://www.animanganews.com/

### ISSUE THREAD

**Issue by RaveN0X87** [ABPindo/indonesianadblockrules#123]
http://www.animanganews.com/p/5-things-to-look-for-before-starting.html?url=IyNNJTFEJTE5JTFGJTFBJTA3RSUwN0VHSyUwNk1LSVpHWlpBRSUwNyUwNyUxMiU1QlglNUMlNUMlNDAjIw%3D%3D

**Comment by gmarcher** [comment]
tambahkan
`animanganews.com#@#.iklan`
`@@||bloggerku.com/safelink/2.0/script.js$script,domain=animanganews.com`
