### ISSUE TITLE
Perihal Lisensi

### ISSUE THREAD

**Issue by Z-Fikar** [ABPindo/indonesianadblockrules#13]
Hi, Saya lihat bahwa repository ini belum mengandung lisensi apapun. Lisensi digunakan untuk mempertegas izin-izin apa saja yang diberikan. Dalam kasus ini program open source, apakah program tersebut dapat disebarluaskan, dimodifikasi, dan apakah proyek tersebut dapat digunakan untuk tujuan komersil.

Untuk repo ini, [ABOindo](https://github.com/ABPindo/indonesianadblockrules), saya sarankan untuk menggunakan [MIT License](http://choosealicense.com/licenses/mit/). Dengan lisensi ini, repo ini memberikan izin sebagai berikut:
- Mendapatkan salinan software ini dan dokumen yang terkait secara gratis
- Dapat menggunakan, menyalin, menggunakan, mempublikasikan, mendistribusikan, dan / atau menjual salinan program ini
Dengan kondisi pengguna:
- Memberikan kredit kepada pemilik program dengan mengikutsertakan pemberitahuan hak cipta dan izin ke dalam salinan software tersebut.

Catatan: Untuk menggunakan lisensi ini anda hanya harus membuat file `LICENSE` agar para pengguna dan komputer tahu bahwa repo ini menggunakan lisensi dan lebih mudah untuk mengaksesnya.

Jika dibutuhkan saya bersedia untuk membuat file `LICENSE` tersebut. :smile: :v: :indonesia:

**Comment by heradhis** [comment]
Terimakasih atas kesediaannya. Perihal lisensi bisa dilihat di /COPYING

**Comment by Z-Fikar** [comment]
Hmm, sekarang saya lihat lagi ternyata sudah lisensi lainnya juga, ada CC-BY-SA dan GPL

Kalau begitu saya tutup isu ini :smile: :v:
