### ISSUE TITLE
bolly4u.asia

### ISSUE THREAD

**Issue by BlazDT** [ABPindo/indonesianadblockrules#132]
bolly4u.asia

Problem: Blocked pictures

Screenshot

https://camo.githubusercontent.com/e707d5a06a0c1014105905466b401224e869302a/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f4d7836504f30492e706e67

Problematic rule:
.bid^$third-party

https://github.com/AdguardTeam/AdguardFilters/issues/40727

**Comment by gmarcher** [comment]
why using 
`ABPindo,
EasyList China,
AdGuard Turkish,
AdGuard Annoyances,
AdGuard French,
AdGuard Base,` if the regional is india?

**Comment by 3xploiton3** [comment]
Why not uncheck abpindo filter?
Because abpindo for indonesian site

Many annoying/crap come from domain .bid

**Comment by BlazDT** [comment]
Thanks for fixing gmarcher.

If the user visits sites of different languages, it is not useful everytime to disable non-applicable languages to the site.
