### ISSUE TITLE
(ask) bagaimana membuat rule filter app tokopedia?

### ISSUE THREAD

**Issue by 3xploiton3** [ABPindo/indonesianadblockrules#133]
Bagaimana cara buat rule filter menghilangkan kolom yang saya lingkari
Aplikasi Tokopedia di android

Kolom ini berisi iklan, sering tidak relevan dengan apa yang kita cari, sangat mengganggu

![](https://i.imgur.com/usSY4T5.jpg)

**Comment by gmarcher** [comment]
Baik itu adaway maupun blokada (saya pakai ini), tidak support menyembunyikan iklan (element hide) di aplikasi android.

**Comment by 3xploiton3** [comment]
@gmarcher saya menggunakan adguard android, 
Sepertinya bisa support element hide, tp tdk tau cara buat rulenya

Tdk seperti di browser yang ada fitur picker

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/pull/137
