### ISSUE TITLE
ezgif.com - incorrect blocking

### ISSUE THREAD

**Issue by Mad182** [ABPindo/indonesianadblockrules#134]
**Berikan URL**
https://ezgif.com/

**Jelaskan masalah**
Blocking images break sites functionality. It prevents image previews.

**Berikan screenshot**
![Screenshot-1](https://user-images.githubusercontent.com/798148/65582827-cda0f400-df86-11e9-9278-6d838d495d8a.png)

**Setting**
any

**Comment by gmarcher** [comment]
Dulu dikarenakan situs tersebut banyak digunakan untuk iklan
