### ISSUE TITLE
manhwa-manga.bid

### ISSUE THREAD

**Issue by AdamWr** [ABPindo/indonesianadblockrules#135]
**Berikan URL**
https://manhwa-manga.bid/

**Jelaskan masalah**
Some pictures are incorrectly blocked.

**Berikan screenshot**
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/65607681-34390880-dfad-11e9-9182-181b4d4f147c.png)

</details>

**Usul sintak filter**
It's caused by:
`.bid^$third-party,domain=~bolly4u.asia`

https://github.com/AdguardTeam/AdguardFilters/issues/40700

**Comment by Hafidzgtg** [comment]
So, what's next ?
