### ISSUE TITLE
https://kazefuri.web.id/

### ISSUE THREAD

**Issue by KagaKouko99** [ABPindo/indonesianadblockrules#136]
**Berikan URL**
... https://kazefuri.web.id

**Jelaskan masalah**
... iklan ada yang tidak terblokir

**Berikan screenshot**
... 
![Annotation 2019-09-27 101048](https://user-images.githubusercontent.com/54178411/65739425-62365e00-e10f-11e9-8434-6008901f46d3.png)

**Setting**
chrome+ublock origin

**Comment by RaveN0X87** [comment]
@gmarcher tolong diupdate masih ada beberapa iklan judi yang belum terblock

**Comment by gmarcher** [comment]
update lagi
