### ISSUE TITLE
blocking generate link

### ISSUE THREAD

**Issue by WaferNabati** [ABPindo/indonesianadblockrules#139]
https://www.eleventhlevelinteractive.com/2019/10/is-affiliate-in-demand.html#?o=d5bd1e687547838d25276d55028b65018969aba267b56906b7a58dd2114026b52d590c4a00e5e580258cb017f4307db3ba68af49cd1035cc5f2314bf4588834d53056dfb77363a3d

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/issues/139
