### ISSUE TITLE
new intermitten fullscreen popup ad in tempo.co

### ISSUE THREAD

**Issue by lmlim** [ABPindo/indonesianadblockrules#14]
dear ABPIndo admin,

i have a request to probe www.tempo.co again. i know most of its ad has been filtered by ABPindo, however since a week ago there has been a new full/partial screen popup ad inside pages.
it is not instantly showed up once you click a link, it is usually popup after several seconds.

i have tried to make my own filter, but it seems the rules are unique everytime i encounter a new one.
please help investigate the site and add to your new rule please....

thanks so much for admin.

===Martin

**Comment by idoenk** [comment]
Dear Martin,

Have you try these filters:

```
||tempo.co/webtorial/like/remodal*
tempo.co##.remodal
```
Let us know if it's work, good luck :)

**Comment by lmlim** [comment]
dear admin,


yes it works... thanks...


________________________________
