### ISSUE TITLE
ganool

### ISSUE THREAD

**Issue by TronID** [ABPindo/indonesianadblockrules#15]
Tolong di tambahkan dalam list filterya. Sering di jumpai di ganool. Terima kasih...
||gk25qeyc.xyz^
||69wnz64h.xyz^
||mosaicolor.website^
||topbananaad.com^
||130.211.230.53^$popup

**Comment by gmarcher** [comment]
ganool yang mana ya? linknya

**Comment by TronID** [comment]
Ganool.is

**Comment by gmarcher** [comment]
terupdate

**Comment by TronID** [comment]
Thanks, Min... Sangat membantu filter di HP juga.

**Comment by TronID** [comment]
Min, Tolong di tambahin filter iklan ini lagi donk... Thanks...
||04dn8g4f.space^
||hlu9tseh.men^
||xbfk51p7.review^
||39o9mcr2.party^

**Comment by gmarcher** [comment]
terupdate

**Comment by TronID** [comment]
Min, 
Cuma 2 list yang terupdate itu pun gk bekerja. Sisa 2 lg tidak terupdate.
Di list:
||04dn8g4f.space$popup,third-party
||xbfk51p7.review$popup

Buat seperti secara manual dia bekerja :
||04dn8g4f.space^$third-party
||hlu9tseh.men^$third-party
||xbfk51p7.review^$third-party
||39o9mcr2.party^$third-party

Thanks...

**Comment by gmarcher** [comment]
update lagi sampai bisa

**Comment by TronID** [comment]
Min, sdh update ulang listnya tetapi masih tetap sama dengan sebelumnya. Tidak ada perubahan.... 
Tolong di cek list donk min....

**Comment by TronID** [comment]
Min, mau tanya. W buka browser di PC sdh tidak ada masalah lagi, tetapi buka browser di Android kok msh tetap bisa muncul iklan yang saya minta block ya ?
Mohon pencerahannya.

**Comment by gmarcher** [comment]
aplikasinya apa? kalau seperti adaway tidak semua filter cocok

**Comment by TronID** [comment]
Pake aplikasi "Adblock for Samsung Internet" (BetaFish).

Sebelumnya minta tambahan filter kok bisa Min....

**Comment by TronID** [comment]
Min, Tambahan filter iklan lagi 
||130.211.212.60^$popup,third-party

Thanks...

**Comment by TronID** [comment]
Min, seperti biasa filter iklan...
||104.198.138.230^$popup,third-party,script

Makasi....

**Comment by TronID** [comment]
Gan, Tolong tambah filter lagi... Thanks
||23.236.55.237^$popup,third-party
||gjol8ib0.website^$third-party
||1wzfew7a.site^$third-party
