### ISSUE TITLE
[nsfw] nekopoi.care

### ISSUE THREAD

**Issue by Arsindy** [ABPindo/indonesianadblockrules#153]
https://nekopoi.care/

iklan judi

**Comment by begundal** [comment]
Network filters
||nekopoi.care/wp-content/uploads/2020/04/QQANGPAO-NekoPoiWEB.gif
Cosmetic filters Click, Ctrl-click
##[src="/wp-content/uploads/2020/04/QQANGPAO-NekoPoiWEB.gif"]
##[href="http://qqangpao.net/"]
##.custom-html-widget.textwidget
##div.side.widget_text:nth-of-type(1)
###sidebar_right
###content
###wrap

**Comment by gmarcher** [comment]
update filtermu
