### ISSUE TITLE
kazefuri.me

### ISSUE THREAD

**Issue by WaferNabati** [ABPindo/indonesianadblockrules#154]
https://kazefuri.me/?id=UWNaOVFWaFBkRUo3czVqczFESFlxamNnNnZPcU9UMnI2eFBZMEdOcnNhL1BoSy9HUXlmU2hWYkNFTERvbWxiaA==

https://kazefuri.me/?id=UWNaOVFWaFBkRUo3czVqczFESFlxb21aYmJTN1RvaFVrWStONEhTMVgvcz0=

popups ads dll

**Comment by gmarcher** [comment]
disini bersih

**Comment by WaferNabati** [comment]
iya udah msk ke eastlist 2 hari yg lalu
