### ISSUE TITLE
smallencode

### ISSUE THREAD

**Issue by p1nkyy** [ABPindo/indonesianadblockrules#16]
Klik button apapun generate new window yang alamatnya: http://aanvxbvkdxph.com/EYD.aspx?c=4019616&a=2880738382&r=1482991851&v=3036093691&l=321&h=%21nWAmdEFns4mkyaR0jSAjHkReOwkpH2RuLB4mn6x6AQzLtGLzIDr6VjLyTQTqFCrvBaoc9KeUneswKT5PvPVx7BcWf71ZM22%2FfDiMcNQC53h%2FJIfK0xf67VlkGlkEIn%2Bp%2FeBONE2qK8ziJEHqthWWt3W7tcYS8w0c9%2F6FNKm0PC9R2mnT2p3raikMVsOzmGIkOnOBUsPDt%2BmgyjFVVbA0lGv1Ri95Q3I7pApVuW2JgTjVOOc1BIPXGnakEplgTIjKFAgowdNNhfMIbvYVxkpL5L%2Fsj%2Bw0vJHHbg93mTPS9nsAb5dd6XuZph8vtpaJuK2Z&s=1366,768,1,1366,768&v=nt.v&m=257,30,98,2607,314,1198,353,12,7,14,-8,-8,1366,595,1382,744 dan ending-nya di alfacart.com serta new tab.
Tolong bantu dibasmi @idoenk

**Comment by idoenk** [comment]
Maybe we're gonna make it this way:

```
! smallencodecom-custom-filters
||dmatquyckwtu.com/*.js
||ompzowzfwwfc.com/*.js
||scbywuiojqvh.com/*.js
||window-close.gq/*.js
```

testing...

**Comment by idoenk** [comment]
Fix: [965720](https://github.com/ABPindo/indonesianadblockrules/commit/9657202db7b524e4048cd3717421d1d6937448c9)

**Comment by p1nkyy** [comment]
Masih belum, bro. Work utk 1-2 klik pertama. Setelah itu saya coba klik link (misal nama aktor / artis) yg redirect ke situs lain, masih kebuka window baru.

**Comment by idoenk** [comment]
Hostnya bnyk uga nih sis.. itu salah satu yg lakuin popup onclick everywhere on body..
Mungkin masih rotating terus, entah sampai seberapa panjang list-nya akan bertambah..

Ini tambahannya, msh di test,
silahken dicoba ditambahkan di custom filter:

```
||rihzsedipaqq.com/*
||zmnqoymznwng.com/*
||gvgakxvukmrm.com/*
```

**Comment by p1nkyy** [comment]
Hihihi, niat juga ya pasang iklannya. OK saya akan add filter tambahan & lapor lg kalo masih banyak. Benernya saya jarang main ke situs ini sih, tapi ya bete juga kalo pas butuh terus dihujani iklan kek gini...
