### ISSUE TITLE
Kompas & Kompasiana - Tampilan webpage crash.

### ISSUE THREAD

**Issue by spartacruz** [ABPindo/indonesianadblockrules#160]
**URL :**
https://www.kompas.com/
https://www.kompasiana.com/
... 

**Issue :**
Ketika abp plus dihidupkan, kedua page tersebut menjadi gagal untuk dirender. (Dugaan saya) Sepertinya abp plus menkill css kompas. Untuk teknisnya, saya kurang paham. Ada kemungkinan iklan ditaruh pada element utama, jadi saat abp memblock element tersebut, secara tidak langsung abp memblock css utama.
...

**Screenshot**

Saat abp + anti adblock killer dihidupkan.
![image](https://user-images.githubusercontent.com/18097823/71638558-e4e23280-2c95-11ea-97f3-266cc6a992f8.png)
![image](https://user-images.githubusercontent.com/18097823/71638569-12c77700-2c96-11ea-988f-8f8f0a74c417.png)

Saat abp **dimatikan**
![image](https://user-images.githubusercontent.com/18097823/71638958-07794900-2ca0-11ea-9d93-8812cd93b8aa.png)
![image](https://user-images.githubusercontent.com/18097823/71638949-d436ba00-2c9f-11ea-8fed-6f6dd79e3eb0.png)

**Setting**
chrome + ABP + Anti adblock killer

**Comment by gmarcher** [comment]
Coba diupdate dulu filternya, di sini normal. Iklan di kompas tidak bisa ditangkal dengan Adblock Plus, coba gunakan [uBlock0](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en)

**Comment by spartacruz** [comment]
Filternya udah diupdate.
Sebenernya masalah ini udah lama terjadi. Kurang lebih 3 - 4 yang lalu.

Cuman baru sekarang2 ini gue posting disini.

Apa memang harus mesti pakai ext lain ya? Atau mungkin filter nya bisa
diperbaharui?

**Comment by gmarcher** [comment]
iya, dulu pernah saya blokir dengan sintak Adblock Plus saja namun merusak halaman seperti di screenshoot, dengan uBlock bisa dihilangkan dengan sintak khusus.
