### ISSUE TITLE
banner pasang iklan disini AWSubs

### ISSUE THREAD

**Issue by lepz0r** [ABPindo/indonesianadblockrules#161]
**Berikan URL**
https://awsubs.tv/

**Jelaskan masalah**
muncul iklan "pasang iklan disini", bisa dihilangkan dengan filter dibawah

**Setting**
firefox+nano adblocker+nano defender

**Usul sintak filter**
`awsubs.tv##.kln.mlb.blox`

**Comment by gmarcher** [comment]
Terimakasih atas laporannya, karena masuk kategori mempromosikan diri sendiri dan tidak mengganggu jadi tidak perlu diblokir.
