### ISSUE TITLE
komikcast.com buka popup ke leoceran.pw

### ISSUE THREAD

**Issue by arifpedia** [ABPindo/indonesianadblockrules#162]
**Berikan URL**
https://komikcast.com/

**Jelaskan masalah**
Saat membuka situs https://komikcast.com di ponsel, saat klik sesuatu akan diredirect ke situs leoceran.pw yang akan membuka Google PlayStore -> Lazada. 

**Berikan screenshot**
**Usul sintak filter**

`||leoceran.pw^`

**Comment by gmarcher** [comment]
Sepertinya domain popupnya gonta-ganti, di tempatku berbeda, kalau masih muncul setelah update tlg dilaporkan lagi
