### ISSUE TITLE
Belum Didukung

### ISSUE THREAD

**Issue by ReksaTresna** [ABPindo/indonesianadblockrules#17]
||gudangmovies21.tv/wp-content/uploads/*.gif

||warungbioskop.com/wp-content/uploads/*.gif
||warungbioskop.com/wp-content/uploads/*.png

||mintafilm.com/wp-content/uploads/*.gif

||jagocinema.com/wp-content/uploads/*.gif
||jagocinema.com/wp-content/uploads/*.png

||app.pegel.pw/wp-content/uploads/*.gif
||film-ganool.co/wp-content/uploads/*.gif

||1m.yt/*.gif
||cmobet.info/wp-content/uploads/*.gif

**Comment by gmarcher** [comment]
update
https://github.com/ABPindo/indonesianadblockrules/commit/c74b300b9195e8dfae246c1616a16afaf46ce63f
https://github.com/ABPindo/indonesianadblockrules/commit/92bd378335f3c9f58414aa736fa6c70ffbae6a90
https://github.com/ABPindo/indonesianadblockrules/commit/08126907430e5d2d646d570b0a5e9ffe4134e1a9
