### ISSUE TITLE
anitoki.com

### ISSUE THREAD

**Issue by exodius48** [ABPindo/indonesianadblockrules#170]
**Berikan URL**
`https://anitoki.com/`
`https://anitoki.com/archives/8086`
`https://anitoki.com/archives/anime/the-god-of-high-school`

**Jelaskan masalah**
Banner ads

**Berikan screenshot**
![1](https://user-images.githubusercontent.com/9832875/91840677-46223180-ec7b-11ea-88ab-4f834f6bb74b.png)

**Usul sintak filter**
... jika punya ide, tuliskan sintak filternya
https://github.com/uBlockOrigin/uAssets/issues/7857

**Comment by gmarcher** [comment]
kalau promosi diri tidak perlu diblokir secara spesifik

**Comment by avie25000** [comment]
filter uBlock origin
`||trakteer.id^$domain=anitoki.com `

**Comment by gmarcher** [comment]
> filter uBlock origin
> `||trakteer.id^$domain=anitoki.com `

FYI it's like "donate with paypal" button, self promotion, so no.
But you can always add it to your personal filter.

Thanks

**Comment by exodius48** [comment]
Thanks broh, solved
