### ISSUE TITLE
iklan judi

### ISSUE THREAD

**Issue by ferilagi** [ABPindo/indonesianadblockrules#175]
**Berikan URL**
lk21c.fun

**Jelaskan masalah**
iklan judi dan lain-lain

**Berikan screenshot**
![lk21](https://user-images.githubusercontent.com/66341611/95047344-177ef700-0710-11eb-8690-717287025fe8.png)

**Usul sintak filter**
... jika punya ide, tuliskan sintak filternya

**Comment by gmarcher** [comment]
terimakasih, update filtermu
