### ISSUE TITLE
Chat widget from https://livechat.com is being blocked.

### ISSUE THREAD

**Issue by MichalPaszowski** [ABPindo/indonesianadblockrules#176]
**Berikan URL**
*.livechat.com
*.livechatinc.com 
...

**Jelaskan masalah**
The adblock list is blocking LiveChat service which is used on many websites for customer service.

Could you please remove it from the list?

**Comment by gmarcher** [comment]
Please give an example of which URL/website is broken?

**Comment by MichalPaszowski** [comment]
That would be https://www.perdigital.com/

**Comment by gmarcher** [comment]
forgive my mistake, thanks
