### ISSUE TITLE
[NSFW] semprot.com and its domain

### ISSUE THREAD

**Issue by HP-N550** [ABPindo/indonesianadblockrules#181]
**Berikan URL**
`https://www.semprot.com/`
`https://rebrand.ly/semprot`
`https://www.semprotyuk.com/`

**Jelaskan masalah**
Unblocked Ads + blank placeholder
Im using ublock origin with default list + ABPIndo + StevenBlack hosts

**Berikan screenshot**
![2021-03-05_205032](https://user-images.githubusercontent.com/80011922/110124326-831adc80-7df4-11eb-884a-d06fd2832cf1.png)
![2021-03-05_205048](https://user-images.githubusercontent.com/80011922/110124332-84e4a000-7df4-11eb-874a-e2dff43f8914.png)

**Usul sintak filter**
... jika punya ide, tuliskan sintak filternya

**Comment by gmarcher** [comment]
Dikarenakan situs ini sangat aktif dan dinamis, saya sarankan melakukan PR

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/pull/215

**Comment by astibinal** [comment]
Komunitas cewek jomblo dan janda muda kesepian, silahkan join : 

https://anggurmerah.xyz/index.php

Forum Cewek Indonesia IGO, Forum BB17 : 

[https://anggurmerah.xyz/index.php](url)

**Comment by kitagas20241** [comment]
gitu aja

www,nobokep,my,id

**Comment by langsungpanas2024** [comment]
ngabis ngabisin aja

www,nobokep,my,id

**Comment by bebaspuas20241** [comment]
mau minta restu

www,nobokep,my,id

**Comment by caripurel2024** [comment]
stop bilang

www,nobokep,my,id

**Comment by maunyagitu2024** [comment]
ff kapan

www,flavaofc,com

**Comment by dirgahayutni2024** [comment]
Dirgahayu TNI

www,flavaofc,com

**Comment by overthemoonnew** [comment]
bang cara ques mini boss gianan

www,kontenterabox,com

**Comment by benedictagisha2025** [comment]
parahhh macett

www,3gpterbaru,com
