### ISSUE TITLE
leon.bet [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [ABPindo/indonesianadblockrules#184]
URL: leon.bet

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/117837267-fb34d100-b281-11eb-9bc6-1813d1bbcf0d.png)

</details>

Caused by `##a[href$="/slots"]` , ABPindo

**Comment by gmarcher** [comment]
fotgot to add comment resolved

https://github.com/ABPindo/indonesianadblockrules/commit/a0ed16b287b34d60079e409dc9fbee683cba05a1
