### ISSUE TITLE
nanimex.com

### ISSUE THREAD

**Issue by What-Zit-Tooya** [ABPindo/indonesianadblockrules#187]
**Berikan URL**

`https://nanimex.com/episode/yugioh-duel-monsters-episode-011`

**Jelaskan masalah**

unblocked ads, when click play button it show up

https://user-images.githubusercontent.com/9832875/131216420-b4a9c796-e5ba-4ed4-b1f8-0175d2de32b1.png

**Usul sintak filter**

Look this https://github.com/uBlockOrigin/uAssets/issues/9845

**Comment by gmarcher** [comment]
terimakasih, sudah ada `nanimex.com##.iklan` jadi elemen hidenya tidak perlu

**Comment by What-Zit-Tooya** [comment]
> 
> 
> terimakasih, sudah ada `nanimex.com##.iklan` jadi elemen hidenya tidak perlu

Iya gan,
Kalau skip `lewati iklan selama 5 detik` bisa dihide apa tidak? maksudnya biar iklannya benar-benar hilang, langsung ke videonya
