### ISSUE TITLE
Use full option names

### ISSUE THREAD

**Issue by mjethani** [ABPindo/indonesianadblockrules#189]
https://github.com/ABPindo/indonesianadblockrules/blob/a186cd327aca9ef8f6ed01734480cc163a01fbcd/src/advert/specific_block.txt#L221

Adblock Plus does not support `$xhr`.

**Comment by mjethani** [comment]
You can [lint your filters](https://github.com/mjethani/flint):

```
npm i -g flint-tool
flint src/advert/specific_block.txt
```

**Comment by gmarcher** [comment]
thanks, that old filter, not needed aanymore

**Comment by mjethani** [comment]
https://github.com/ABPindo/indonesianadblockrules/blob/b43d1cfb8c7a81a9613911338ccb1c1849d80231/src/advert/specific_block.txt#L228

I think this should be `$third-party`.

**Comment by mjethani** [comment]
Two more issues from the linter:

```
abpindo+easylist.txt:58792: WARNING: javascript: looks like an unanchored protocol

javascript:$popup,domain=pirateproxy.live|thehiddenbay.com|thepiratebay.org

abpindo+easylist.txt:62844: ERROR: Extra anchor before data:

@@||data:text^$popup,domain=box.com|clker.com|labcorp.com|zipit.io
```

In the first case, it wants a `|` before `javascript:`.

The second one is definitely an error because `||data:text^` is not going to match anything. There should be only one `|` before `data:`.

PS: Now you can [set up the linter in your repo using GitHub Actions](https://gist.github.com/mjethani/eb43063309fde1fce1b29b95304a68b0).

**Comment by mjethani** [comment]
> Two more issues from the linter

Sorry, it looks like both of these issues are from EasyList: https://github.com/easylist/easylist/pull/8971 and https://github.com/easylist/easylist/pull/8972.

**Comment by gmarcher** [comment]
> 
> 
> > Two more issues from the linter
> 
> Sorry, it looks like both of these issues are from EasyList: [easylist/easylist#8971](https://github.com/easylist/easylist/pull/8971) and [easylist/easylist#8972](https://github.com/easylist/easylist/pull/8972)

yep no problem, it's from easylist
