### ISSUE TITLE
Komik site

### ISSUE THREAD

**Issue by Reoldyk** [ABPindo/indonesianadblockrules#19]
jika klik link buat baca komik, tiba - tiba muncul popup di dua situs ini.
http://mangaindo.web.id/
https://kombatch.com/

browserku firefox 51.0.1
uBlock Origin 1.11.1rc0

**Comment by gmarcher** [comment]
Makasih masukannya, purge+update abpindo  mu

**Comment by Reoldyk** [comment]
terimakasih sudah di respon, tapi masih ada masalah.
di mangaindo kadang masih muncul popup tab-nya.
di kombatch, tampilan web-nya jadi rusak.
![screenshot-kombatch com-2017-02-25-22-04-11](https://cloud.githubusercontent.com/assets/4547317/23332124/bc83aa9e-fba6-11e6-8e61-bd988a518353.png)
