### ISSUE TITLE
m.jpnn.com (on mobile)

### ISSUE THREAD

**Issue by monzta** [ABPindo/indonesianadblockrules#198]
**Berikan URL**

https://m.jpnn.com/news/bea-cukai-sita-puluhan-ribu-batang-rokok-ilegal-di-pekanbaru-dan-bandung

**Jelaskan masalah**
unblocked, floating ad for a game

**Berikan screenshot**

![m jpnn com](https://user-images.githubusercontent.com/8057368/145590836-68affeea-3f18-4565-9cbd-2eca3cabbe16.jpg)

**Usul sintak filter**

`jpnn.com##.bx_wrapper_float_icon` 

or blocking this script: `https://api.flygame.io/sdk/widget/id_jpnn.1540.js`

**Comment by gmarcher** [comment]
thanks, sorry for the delay in responding
