### ISSUE TITLE
Placeholder on sindonews.com (mobile)

### ISSUE THREAD

**Issue by edivaniadc** [ABPindo/indonesianadblockrules#208]
**Berikan URL**
https://international.sindonews.com/read/628415/43/tragis-pangeran-arab-saudi-mohammed-bin-nayef-meninggal-di-penjara-1639494740

**Jelaskan masalah**
Empty placeholder on the top > Mobile emulation

**Berikan screenshot**
<img width="1113" alt="is" src="https://user-images.githubusercontent.com/57706597/146780422-19f28a14-f997-4732-9800-033b7cc3d1e5.png">

**Usul sintak filter**
##.parallax-ad
###me-div-gpt-ad-parallax

**Comment by edivaniadc** [comment]
@gmarcher could you please also add `##.parallax-close` to hide the close button (top right corner > Mobile emulation). Thank you for your time.

**Comment by gmarcher** [comment]
sorry, i leave it like that. because if i hid close button, we get big blank spot.
