### ISSUE TITLE
Q: Anti-Adblock Killer

### ISSUE THREAD

**Issue by indrakaw** [ABPindo/indonesianadblockrules#21]
Ada namanya [reek/anti-adblock-killer](https://github.com/reek/anti-adblock-killer)

Penjelasan: 
https://www.bersosial.com/threads/upgrade-adblock-anda-dengan-anti-adblock-killer.39214/

Q: Apakah ini akan menyebabkan konflik?

**Comment by heradhis** [comment]
Tidak
Anggap saling melengkapi, saya sendiri pakai itu dan tidak menemui kendala. Kalaupun nanti sewaktu dipasang melewatkan iklan tertentu, pasti masih dalam batas wajar.
