### ISSUE TITLE
iklan pada sempr.t

### ISSUE THREAD

**Issue by Rh354** [ABPindo/indonesianadblockrules#22]
gan semprot ganti sekarang ke
`
http://46.166.167.16/`

bookmark link kalau misalnya ganti lagi disni biasannya
`
http://tinyurl.com/cintasemprot`

jadi yg lolos ada 4 image

```
http://188affiliates.com/newmedia/indo/Mediasoccernews/indoSbnG_400x50.gif
https://www.gambar123.com/xf/trump/xyz_nation303_2017_01_17.gif
https://www.gambar123.com/xf/trump/xyz_klix4d_2017_02_16.gif
https://www.gambar123.com/xf/trump/xyz_kbookie_2017_02_15.gif
```

Solusi
tambahkan ini gan

```
||188affiliates.com^$third-party
||gambar123.com/xf/
46.166.167.16##.warning
46.166.167.16##[class^="semprotnenenmontok_"]
```

btw tanya donk koq 188affiliates.com di allow di 46.166.167.16, semprot.com, semprotku.com ?

**Comment by heradhis** [comment]
sini pakai speedy Gan, keblokir. kalau bisa pakai pull request jadi enak updatenya

**Comment by Rh354** [comment]
dah di pull gan

**Comment by kitagas20241** [comment]
tolong yahhh

www,nobokep,my,id

**Comment by langsungpanas2024** [comment]
its that boss

www,nobokep,my,id

**Comment by bebaspuas20241** [comment]
so siap

www,nobokep,my,id

**Comment by caripurel2024** [comment]
ga tau

www,nobokep,my,id

**Comment by maunyagitu2024** [comment]
gitu yah

www,flavaofc,com

**Comment by dirgahayutni2024** [comment]
brimomudah serbabisa

www,flavaofc,com

**Comment by overthemoonnew** [comment]
pagi bangggggg, like dulu gak sih

www,kontenterabox,com

**Comment by benedictagisha2025** [comment]
parahhh macett

www,3gpterbaru,com

**Comment by MulaiBarengBSN** [comment]
MulaiBarengBSN

#MulaiBarengBSN

www,kesiangan,com
www.kesiangan.com
