### ISSUE TITLE
blank di redirect site seperti manteb.in

### ISSUE THREAD

**Issue by Rh354** [ABPindo/indonesianadblockrules#23]
beberapa situs redirect seperti manteb.in terblokir semua untuk isinya gan. padahal yang dibutuhkan cuma tulisan **klik Di Sini**

bisa tolong dicek gan. untuk salah satu contoh sitenya ini gan `http://manteb.in/iTN81 `

**Comment by gmarcher** [comment]
Terimakasih laporannya, silahkan update paksa abpindo
