### ISSUE TITLE
Disqus embedded dan website tidak bisa dibuka

### ISSUE THREAD

**Issue by heywolf15** [ABPindo/indonesianadblockrules#231]
d231vab146qzfb.cloudfront.net

Disqus tidak bisa terbuka karena ada url yg di block

![firefox_o6WhY6OOjO](https://user-images.githubusercontent.com/34807171/150169542-4707a0e2-88f8-49f9-9642-dd8e29238391.png)

**Comment by gmarcher** [comment]
terimakasih laporannya, silakan update paksa filtermu
https://github.com/ABPindo/indonesianadblockrules/commit/1ad24488152e33b39daf17f67e7e6e15a955bf60
