### ISSUE TITLE
Goody.to (Update Filter)

### ISSUE THREAD

**Issue by TronID** [ABPindo/indonesianadblockrules#24]
Gan, Tolong tambahkan filter... Thanks
||23.236.55.237^$popup,third-party
||gjol8ib0.website^$third-party
||1wzfew7a.site^$third-party

**Comment by TronID** [comment]
Ini lagi Gan...
||charmstroy.info^$popup,third-party dari http://extratorrent.cc

Thanks

**Comment by TronID** [comment]
Update: ||104.197.157.168^$popup,third-party

Thanks

**Comment by TronID** [comment]
Update lagi... Gan
||104.198.156.187^$popup,third-party

Thanks

**Comment by TronID** [comment]
Update lagi...
||104.198.134.30^$popup,third-party

**Comment by gmarcher** [comment]
kalau mau cepat updatenya buat pull request saja

**Comment by TronID** [comment]
Okay. Ke depan saya akan buat di Pull Request. Thanks...

**Comment by TronID** [comment]
Gan, kok gk bs buat New Pull Request ? 
Mau update filter lagi...
||104.197.207.200^$popup,third-party

**Comment by gmarcher** [comment]
coba lagi, siapapun bisa PR di sini kok

**Comment by TronID** [comment]
Gan, sudah w klik Pull Request jd muncul gini.... Gmn tuh ? 

![2017-05-22_142818](https://cloud.githubusercontent.com/assets/24579056/26296929/01209a12-3efb-11e7-81f8-79cfdc9516e4.jpg)

**Comment by gmarcher** [comment]
Paling mudah klik tanda pensil
![screenshot 105](https://cloud.githubusercontent.com/assets/12405001/26301593/dccce966-3f0b-11e7-9e67-913f392e8a7e.png)
lengkapnya
saya pakai tutorial ini Gan
https://www.youtube.com/watch?v=YTbRzhQju4c

untuk iklan seperti diganol, masukkan di https://github.com/ABPindo/indonesianadblockrules/blob/master/abpindo_adservers.txt
