### ISSUE TITLE
Site report

### ISSUE THREAD

**Issue by ghost** [ABPindo/indonesianadblockrules#242]
**Berikan URL**
emputogel.com

**Jelaskan masalah**
Annoyance (judi)

 **Usul sintak filter**
emputogel.com
0.0.0.0 emputogel.com
||emputogel.com^
*emputogel.com

**Comment by gmarcher** [comment]
tolong diberikan URL yang ada iklan tersebut?

**Comment by CpqtTpEBxo** [comment]
http://m.emputogel.com

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/8d8b0936df13bd3162aed93148adcc5788c8f072
