### ISSUE TITLE
Membuat filter

### ISSUE THREAD

**Issue by O7zSO31IVg** [ABPindo/indonesianadblockrules#249]
Bagaimana cara membuat filter untuk Adblock Plus menggunakan python-abp seperti abpindo

**Comment by gmarcher** [comment]
1. install python
2. install python-abp
`pip install --upgrade python-abp`
3. buat abpindo.template subcription
```
[Adblock Plus 2.0]
! Title: ABPindo
! Description: Filter tambahan untuk EasyList memblokir iklan berbahasa Indonesia dan Malaysia.
! Last modified: %timestamp%
!---------------------- advert blocking filters ----------------------!
%include abpindo:src/advert/adservers.txt%
%include abpindo:src/advert/thirdparty.txt%
```
4. buka terminal jalankan perintah 
`flrender -i abpindo=. abpindo.template subscriptions/abpindo.txt`

**Comment by O7zSO31IVg** [comment]
Kalo untuk visual studio code bisa gak?

**Comment by gmarcher** [comment]
bisa, saya juga pakai itu

**Comment by O7zSO31IVg** [comment]
Terimakasih jawabannya
