### ISSUE TITLE
[nsfw] https://manhwaid.org/

### ISSUE THREAD

**Issue by YellowStar11** [ABPindo/indonesianadblockrules#263]
**Berikan URL**
https://manhwaid.org

**Jelaskan masalah**
Iklan pop up anti virus muncul

**Berikan screenshot**
![Screenshot_2022-02-15-08-03-45-570_com brave browser](https://user-images.githubusercontent.com/98148960/153974373-3fee1a1e-f0e7-4e6e-8f07-50b1b71032d1.png)

**Usul sintak filter**
...

**Comment by gmarcher** [comment]
limited by brave browser, use ublock and update your filter
