### ISSUE TITLE
Lisensi

### ISSUE THREAD

**Issue by O7zSO31IVg** [ABPindo/indonesianadblockrules#264]
Apakah lisensi yang ABPindo gunakan GPLv3, atau CC-BY-SA?

**Comment by gmarcher** [comment]
keduanya, seperti [easylist](https://easylist.to/pages/licence.html)

**Comment by O7zSO31IVg** [comment]
> keduanya, seperti [easylist](https://easylist.to/pages/licence.html)

Kenapa harus keduanya, tidak salah satu saja?

Dan bagaimana jika saya ingin menggunakan beberapa bagian dari filter ABPindo untuk proyek saya yang lain? Apa yang harus saya lakukan?

**Comment by gmarcher** [comment]
Bisa disahre, edit, digunakan kembali, dengan diberi lisensi yang sama dan dengan diberi sumbernya.

**Comment by O7zSO31IVg** [comment]
> Bisa disahre, edit, digunakan kembali, dengan diberi lisensi yang sama dan dengan diberi sumbernya.

Terimakasih informasinya sangat membantu
