### ISSUE TITLE
InternetSehat menyusup ke  ABPindo/adblock?

### ISSUE THREAD

**Issue by lmlim** [ABPindo/indonesianadblockrules#27]
halo admin,

beberapa hari terakhir saya perhatikan ABPindo mulai memblock site2/url yang di block oleh "InternetSehat", menurut saya ini sudah diluar batas dan ini sangat menggangu. karenan ABPindo itu murni untuk block ADS... dan BUKAN Censorship.

saya protes terhadap diikut sertakannya blacklist InterSehat di dalam ABPindo.

mohon dipertimbangkan dan dikembalikan ke fungsi semula, terima kasih.

===

**Comment by onmyouji** [comment]
@lmlim 

Kalau boleh tahu, website/URL apa yang disensor?

**Comment by gmarcher** [comment]
Iya pertanyaannya sama dengan @onmyouji , URL yang mana? kalau ada situs yang rajin dikunjungi lebih baik di whitelist

Kalau mau pakai yang tanpa nawala gunakan subscription ini
`https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo_tanpanawala.txt`

**Comment by lmlim** [comment]
terima kasih onmyouji dan gmarcher untuk reply nya,

saya akan coba link yang diberikan di atas dulu untuk sementara.

thanks
====

**Comment by gmarcher** [comment]
coba deh sekarang pakai abpindo yang biasa, bukan yang tanpa nawala. apakah masih bermasalah? filter sudah ditambahi  tag "third-party" harusnya kalau dikunjungi langsung tidak akan diblock. 
kalau masih ada usul, bisa di komen disini
