### ISSUE TITLE
product ad container on tribunnews . com

### ISSUE THREAD

**Issue by manuel-martinez-dev** [ABPindo/indonesianadblockrules#270]
**Berikan URL**
www.tribunnews.com

*Example page:*
https://www.tribunnews.com/shopping/2022/02/23/ace-hardware-guyur-konsumen-dengan-diskon-hingga-70-persen-di-boom-sale

**Jelaskan masalah**
There's an ad container at the bottom of articles pages, their redirect and popups are already blocked by the list, so clicking on them does nothing.
Why not hide them also? :)

**Berikan screenshot**
![image-tribunnews](https://user-images.githubusercontent.com/40897997/155314391-4a328d4c-cc46-4ebc-8a29-9f891006d4f1.png)

**Usul sintak filter**
`tribunnews.com##.belanja-picks`

**Comment by gmarcher** [comment]
Thanks

**Comment by rigaz29** [comment]
need update
tribunnews.com##div[class*="ads-placeholder"]
