### ISSUE TITLE
Mangakita

### ISSUE THREAD

**Issue by Reoldyk** [ABPindo/indonesianadblockrules#28]
kalo pas klik di area bukan gambar atau link, pasti muncul pop up newtab.
dan itu rasanya cukup mengganggu, tolong di blok.

sample link http://www.mangakita.net/hunter-x-hunter-chapter-363-bahasa-indonesia/

dan ada beberapa banner iklan di disitus ini yg masih belum di blok filer IDN: ABPindo.
tolong di cek.
https://kombatch.com
http://komikcast.com/
http://neumanga.tv/
![untitled](https://user-images.githubusercontent.com/4547317/27971472-03823814-637d-11e7-8043-0b7e3758217d.png)

![unggtitled](https://user-images.githubusercontent.com/4547317/27971473-0383cf62-637d-11e7-8184-5acf86ea6036.png)

![untffitled](https://user-images.githubusercontent.com/4547317/27971705-dd194e6e-637d-11e7-8755-cd715037ce10.png)

terimakasih.

**Comment by Reoldyk** [comment]
skrng mangakita ganti tampilan, dan kalo klik di tempat kosong.
sering muncul popup, tolong di cek.
csample link http://www.mangakita.net/one-piece-chapter-877-bahasa-indonesia/

**Comment by Reoldyk** [comment]
dan tolong blokir iklan di situs ini juga.

![untithhhled](https://user-images.githubusercontent.com/4547317/29930767-83d27dc0-8e99-11e7-8b4c-eb7597d7cca7.png)
sample link http://mangaku.web.id/one-piece-chapter-877-aku-tidak-semanis-itu/


![untfffffitled](https://user-images.githubusercontent.com/4547317/29930798-9ef85cc8-8e99-11e7-9edd-237495a8af64.png)
sample link http://jagatplay.com/2017/08/news/god-of-war-lepas-beberapa-artwork-baru/



![un55titled](https://user-images.githubusercontent.com/4547317/29930837-c2c2184c-8e99-11e7-84be-916a1e8f501b.png)
sample link http://mangashiro.net/



![untit888led](https://user-images.githubusercontent.com/4547317/29930876-e116a9c0-8e99-11e7-9229-040792e340fc.png)
sample link http://neumanga.tv/

**Comment by gmarcher** [comment]
`http://mangaku.web.id/one-piece-chapter-877-aku-tidak-semanis-itu/`
tidak ada masalah disini
`http://jagatplay.com/2017/08/news/god-of-war-lepas-beberapa-artwork-baru/`
tidak terlalu mengganggu
`http://mangashiro.net/`
tidak kelihatan iklannya
`http://neumanga.tv/`
update filternya

Sebagai info, semenjak pakai [uBlock Origin](https://github.com/gorhill/uBlock#installation) saya langganan filter dari adguard, karena banyak filter tambahannya yang cocok dengan uBlocko
English: `https://adguard.com/en/filter-rules.html?id=2`
Privacy: `https://adguard.com/en/filter-rules.html?id=3`

**Comment by Reoldyk** [comment]
makasih info filternya,
lngsung aku tambahkan ke ublock origin-ku.

**Comment by Reoldyk** [comment]
tolong cek Kombatch, pas klik link selalu muncul popup ini.
https://dsf4t5jfds34j.com/1234969.html?q

sudah coba pake filter ini, tapi masih muncul saja.
||dsf4t5jfds34j.com^$popup,third-party
