### ISSUE TITLE
https://manhwalist.com/ (Animated ads)

### ISSUE THREAD

**Issue by edivaniadc** [ABPindo/indonesianadblockrules#289]
**Berikan URL**
https://manhwalist.com (home page and article pages)

**Jelaskan masalah**
Block animated banner ads

**Usul sintak filter**
`||images2.imgbox.com^$image,domain=manhwalist.com`

**Berikan screenshot**
<img width="920" alt="mhc" src="https://user-images.githubusercontent.com/57706597/158823834-ad3cb7de-7e5b-4aa9-9ed8-09d4a2b65419.png">
<img width="960" alt="mhv" src="https://user-images.githubusercontent.com/57706597/158823848-b27c81fb-c40a-49f5-bb35-78f0e2ca3a18.png">

**Comment by edivaniadc** [comment]
Hi @gmarcher when you have the chance, could you please have a look at this issue? thank you in advance.

**Comment by sabinahschmitz** [comment]
Hey @gmarcher Wanted to follow up on this ticket. Thank you very much!

**Comment by gmarcher** [comment]
sorry to take long time, please update your filter
