### ISSUE TITLE
Q: Apakah bisa build hosts file?

### ISSUE THREAD

**Issue by dikiaap** [ABPindo/indonesianadblockrules#29]
Saya ingin menaruh berbagai situs judi, berita hoax, porno yang ada di Indonesia di /etc/hosts file. Sebenarnya ini seperti punyanya https://github.com/StevenBlack/hosts , tapi untuk Indonesia.
Jadi kepinginnya bisa multiple devices dan bisa saya tambahkan di ponsel saya yang memakai AdAway.

Apakah ada yang tahu mengenai daftar-daftar/repo untuk blacklist ini?

**Comment by gmarcher** [comment]
Setahu saya nawala
http://www.nawala.id/statistik/domain-tertapis/domain-tertapis-2?wptouch_preview_theme=enabled
`http://www.nawala.id/wp-content/uploads/2014/08/list_situs_scam.txt`
`http://www.nawala.id/wp-content/uploads/2014/08/list_situs_judi.txt`
sama trust positif 
http://trustpositif.kominfo.go.id/files/downloads/index.php?dir=
kalau ada yang lain saya tolong diberitahu.

**Comment by dikiaap** [comment]
Thanks!

Soalnya saya pakai dnscrypt, jadi saya butuh ini. :smiley:
Saya make yang nawala. Tapi kurang update. :(

**Comment by dikiaap** [comment]
Jika ada yang butuh file hosts yang saya maksud, saya sudah generate yang dari nawala. Tapi untuk AdAway dan cuma scam sama judi.

Jika ingin memakai 0.0.0.0 seperti di repositori StevenBlack, silahkan replace 127.0.0.1 melalui teks editor kesukaan kalian.

https://gist.github.com/e3a2d3545d762cad76761283447608be

**Comment by dikiaap** [comment]
Jika ada yang butuh file hosts yang saya maksud, saya sudah generate yang dari nawala. Tapi untuk AdAway dan cuma scam sama judi.

Jika ingin memakai 0.0.0.0 seperti di repositori StevenBlack, silahkan replace semua 127.0.0.1 melalui teks editor kesukaan kalian.

Halaman Gist: https://gist.github.com/e3a2d3545d762cad76761283447608be 

Raw: https://gist.githubusercontent.com/dikiaap/e3a2d3545d762cad76761283447608be/raw/8f085e72d4d1e1e6cc02755610413d957d20b1e7/daftar-situs-scam-dan-judi.txt
