### ISSUE TITLE
Web Yang Belum Ditambahkan

### ISSUE THREAD

**Issue by realodix** [ABPindo/indonesianadblockrules#30]
Beberapa website yang mungkin perlu untuk ditambahkan:

- [x] lk21.co
- [x] layarkaca21.us
- [x] movie303.com
- [x] sukamovie.id
- [x] nonton33.tv
- [x] nontonin.com
- [x] nontononlinedrama.co
- [x] nontondrama.me
- [x] film-drama.co
- [x] n21.tv
- [x] cinemaqq.com
- [x] satujiwa.org
- [x] nontonsub.com

**Comment by bektigalan** [comment]
kat torrent gan, [thekat.se](thekat.se)

**Comment by realodix** [comment]
Beberapa web yang mungkin perlu ditambahkan. Yang gak perlu coret aja.

- [ ] http://123drakor.com/
- [ ] http://www.21boxoffice.com/
- [ ] http://bioskop007.me/
- [ ] http://www.bioskop212.ga/
- [ ] http://bioskop90.me/
- [ ] http://cinemaindoweb.com/
- [ ] http://cinemamovie365.com/
- [ ] https://idbioskop.com/
- [ ] http://indocinema21.com/
- [ ] http://indoxxi.info/ (di abpindo.txt indoxxi.net)
- [ ] http://indoxxi.top/ (di abpindo.txt indoxxi.net) 
- [ ] https://www.layarcinema.com/
- [ ] http://www.movie303.com/
- [ ] http://no99.me/ (di abpindo.txt nontononline99.com)
- [ ] http://www.nonton77.com/
- [ ] https://nontoncinema.org/
- [ ] http://nontonfilm12.com/
- [ ] http://nontonfilm21.top/ (di abpindo.txt nontonfilm21.club)
- [ ] http://www.nontonmovie303.com/
- [ ] http://nontononline99.club/ (di abpindo.txt nontononline99.com)
- [ ] http://nontonxxi.co/
- [ ] http://numpangnonton.com/
- [ ] http://ns21.me/ (di abpindo.txt ns21.org)
- [ ] http://www.senimovies.net/
- [ ] http://sinemaindo.web.id/ (sepertinya sudah ada di abpindo.txt, namun masih ada beberapa iklan yg muncul di halaman depan dan setiap halaman movie)
- [ ] http://sukamovie.mobi/
- [ ] https://www.sukamoviedrama.co/

**Comment by gmarcher** [comment]
bisa bantu buat filternya? lalu nanti buat pull request? situs2 ini soalnya biasanya umur domainnya cuma sebentar.

**Comment by realodix** [comment]
- [ ] http://nontonfilm77.me/
- [ ] http://nontonbioskop21.org/
- [ ] http://www.nontonbioskop.online/

**Comment by gmarcher** [comment]
kalau ada tambahan tolong buat PR
