### ISSUE TITLE
Placeholders on radenku.com

### ISSUE THREAD

**Issue by rigaz29** [ABPindo/indonesianadblockrules#312]
**Berikan URL**
[radenku.com](https://radenku.com/cara-install-passwall-openwrt/)

**Jelaskan masalah**
Placeholders on the bottom site

**Berikan screenshot**

**Usul sintak filter**
radenku.com##[class*="sticky-ads"]

**Comment by rigaz29** [comment]
need update
!radenku.com##.code-block

**Comment by gmarcher** [comment]
the sites clean, and that DOM should only for spesific code block
you can add to personal filter
