### ISSUE TITLE
Iklan judi terlepas di https://www.ngefilm21.top/?m=1

### ISSUE THREAD

**Issue by willjones911** [ABPindo/indonesianadblockrules#324]
Berikan URL
https://www.ngefilm21.top/?m=1

Jelaskan masalah
iklan judi jenis gif dimainkan di mobile dan nvidia shield tv pro didalam mozilla firefox nightly bersama ublock,filter sudah di updatekan, di windows iklannya tiada tapi di mobile ada lagi sama seperti di nvidia shield tv pro. screenshot sudah ditambahkan dibawah,maaf bahasa indonesia bukan bahasa pertama saya

Berikan screenshot
https://imgur.com/a/t7j4nue

ublock log

uBlock Origin: 1.42.4
Firefox Mobile: 101
filterset (summary):
network: 170609
cosmetic: 140456
scriptlet: 52931
html: 647
listset (total-discarded, last updated):
removed:
ublock-quick-fixes: null
added:
https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt: 7253-141, 2h.36m
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock.txt: 25731-243, 2h.36m
https://winhelp2002.mvps.org/hosts.txt: 8730-348, 2h.36m
adguard-generic: 63786-5993, 2h.36m
adguard-spyware: 25838-1117, 2h.36m
adguard-spyware-url: 551-4, 2h.36m
block-lan: 43-0, 2h.36m
curben-phishing: 13460-2, 2h.36m
curben-pup: 270-0, 2h.36m
adguard-annoyance: 51995-4557, 2h.36m
adguard-social: 16826-1648, 2h.36m
fanboy-thirdparty_social: 68-1, 2h.36m
fanboy-annoyance: 68587-57286, 2h.36m
fanboy-cookiemonster: 29812-14796, 2h.36m
fanboy-social: 23289-13575, 2h.36m
ublock-annoyances: 4363-7, 2h.36m
dpollock-0: 10364-1657, 2h.36m
IDN-0: 8997-3568, 2h.36m
default:
user-filters: 2-0, never
ublock-filters: 31226-3360, 2h.36m
ublock-badware: 4081-3, 2h.36m
ublock-privacy: 216-1, 2h.36m
ublock-abuse: 74-0, 2h.36m
ublock-unbreak: 1777-0, 2h.36m
adguard-mobile: 7584-237, 2h.36m
easylist: 65987-24830, 2h.36m
easyprivacy: 26824-10736, 2h.36m
urlhaus-1: 7537-0, 2h.36m
plowe-0: 3682-3, 2h.36m
filterset (user): [array of 2 redacted]
trustedset:
added: [array of 14 redacted]
removed:
chrome-extension-scheme
chrome-scheme
switchRuleset:
removed:
no-csp-reports: * true
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats:
allReadyAfter: 1885 ms (selfie)
maxAssetCacheWait: 629 ms

**Comment by dave9123** [comment]
Navigate to the uBlock Origin settings.
Select the "Filter lists" tab.
Scroll to the "Custom" section, at the bottom.
Select "Import...".
Add `https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt`.
Select "Apply changes" at the top of the page.
