### ISSUE TITLE
[Check] Dead Domain

### ISSUE THREAD

**Issue by gmarcher** [ABPindo/indonesianadblockrules#325]
## Berikan URL
..
## Jelaskan masalah
Domain mati

## Berikan screenshot (pilihan)
..
## Lingkungan pengujian
- [x] Firefox
- [ ] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter
...

**Comment by dave9123** [comment]
URL domainnya?
