### ISSUE TITLE
gtm tokopedia dalam whitelist

### ISSUE THREAD

**Issue by bbn-bernard** [ABPindo/indonesianadblockrules#33]
tolong hapus gtm untuk tokopedia dalam whitelist.

https://github.com/ABPindo/indonesianadblockrules/blob/master/abpindo_whitelist.txt#L31

gtm termasuk tracker dalam EasyPrivacy.

**Comment by onmyouji** [comment]
Mo pastiin aja, gtm kalau diblok mempengaruhi kerja website gak?

Kayaknya tokopedia suka ngaco kalau ada script yang diblock.

**Comment by heradhis** [comment]
https://screenshots.firefox.com/uGopJQO6DD5w8iQK/www.tokopedia.com
Itu buat fitur tokopedia, saya sendiri menyarankan kalau berbelanja di situs favorit pemblokir iklan di whitelist saja.

**Comment by bbn-bernard** [comment]
Iya beberapa fitur web bisa jadi ngaco. Ini udah resiko pengguna. Kalau mau buat whitelist pribadi saja.

Cuma isunya bukan itu. Masalahnya kalau tokopedia dibiarin, kenapa yang lain tidak? Perusahaan rela "bayar" supaya bisa masuk whitelist daftar seperti ini. Kalau sudah begitu daftar ini sudah tidak bisa dipercaya lagi. Catatan bahwa daftar seperti ini tujuannya memang membuat daftar aturan tracker/penginklan. 

Saya sendiri menyarankan whitelist pribadi (lokal - untuk kepentingan pribadi) mengingat blokir gtm bersifat global, dan daftar aturan di repo ini sudah dijadikan referensi beberapa tools blokir tracker/pengiklan.
