### ISSUE TITLE
[info] annoyance to adult

### ISSUE THREAD

**Issue by gmarcher** [ABPindo/indonesianadblockrules#336]
https://github.com/ABPindo/indonesianadblockrules/commit/a0292467c6b1f5fe6922b0aa68aefeb22b42c52a

Latar belakang:
ABPindo pada awalnya menggunakan kategori annoyance untuk memfilter iklan judi, namun seiring waktu pada [Easylist](https://secure.fanboy.co.nz/fanboy-annoyance.txt)/ [Adguard](https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/annoyances.txt)/ [uBlock](https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/annoyances.txt) menggunakan kategori annoyance untuk memfilter elemen social & cookies. 

ABPindo ingin memperjelas bahwa ABPindo tidak memblokir elemen annoyance (social media dan cookies). Selanjutnya mengkategorikan iklan judi sebagai adult. Filter ABPindo secara bawaan memfilter semua iklan (termasuk iklan adult/judi) sesuai [kebijakan](https://easylist.to/pages/policy.html). Perubahan ini akan diikuti dengan pergantian tautan, wiki dan lain-lain secara bertahap. Jika menemukan kesalahan typo atau broken link bisa membuat issue.

Terimakasih

**Comment by arfshl** [comment]
#344 dan #345
