### ISSUE TITLE
Link situs judi yang belum di block

### ISSUE THREAD

**Issue by avimuh** [ABPindo/indonesianadblockrules#339]
## Berikan URL (gunakan kode)
`ada dibawah`

## Jelaskan masalah (issue)
Link judi tersebut belum terblokir oleh adpindo

## Lingkungan pengujian (beri tanda x)
- [x] Firefox
- [ ] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus
- [x] Adguard Home

## Usul sintak filter
```||klikkusite.com^
||investopedia.link^
||qlink.id^
||69702145.net^
||69702145.xyz^
||jadi123rtp.online^
||luxury138.link^
||ps307.org^
||oer2go.org^
||englandforever.org^
||mpftgw.apps-dev-hq.intranet.undp.org^
||merrittlandhort.com^
||matri-archi.com^
||indoxbet.us^
||msilc.org^```

**Comment by gmarcher** [comment]
Mohon maaf dikarenakan tidak ada URL untuk melakukan pengetesan, saya tutup issue ini. Selanjutnya jika bisa memberikan URL testnya, bisa dibuka kembali. Terimakasih
