### ISSUE TITLE
Blok iklan telkomsel

### ISSUE THREAD

**Issue by fikrillah** [ABPindo/indonesianadblockrules#343]
## Jelaskan masalah (issue)
Says menggunakan telkomsel di firefox android dengan uBlock. Terkadang muncul iklan telkomsel pada beberapa random site

## Berikan screenshot (pilihan)

![Screenshot_20220626-104602_Iceraven](https://user-images.githubusercontent.com/48489341/175799084-6331087c-1b56-42a3-a7d7-b142abd066c5.png)

## Lingkungan pengujian (beri tanda x)
- [x] Firefox
- [ ] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter

||offdeck.telkomsel.com^

**Comment by arioki1** [comment]
dah tak buat pr di sini
https://github.com/ABPindo/indonesianadblockrules/pull/350

**Comment by arioki1** [comment]
issue ini sepertinya bisa di tutup karena PR sudah di merge @fikrillah

**Comment by gmarcher** [comment]
Terimakasih sudah melakukan PR, issue seperti ini memang lebih cepat jika ada yang melakukan PR

> issue ini sepertinya bisa di tutup karena PR sudah di merge @fikrillah
