### ISSUE TITLE
iklan judi di http://107.152.43.215/ rutin21

### ISSUE THREAD

**Issue by willjones911** [ABPindo/indonesianadblockrules#348]
## Berikan URL (gunakan kode)
(http://107.152.43.215/)

## Jelaskan masalah (issue)
iklan judi di website diatas didalam firefox mobile

## Berikan screenshot (pilihan)
https://i.imgur.com/IJ2JDmJ.jpg
https://i.imgur.com/rBdiDHI.jpg

## Lingkungan pengujian (beri tanda x)
- [ X] Firefox
- [ ] Chrome
- [X ] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter
... jika punya ide, tuliskan sintak filternya

**Comment by willjones911** [comment]
iklan masih ada, dalam firefox nightly android dan firefox android biasa sudah update filterlist tapi masih sama

**Comment by gmarcher** [comment]
karena situsnya seumur jagung, saya tutup issue ini
