### ISSUE TITLE
Error: Failed to execute 'insertRule' on 'CSSStyleSheet'

### ISSUE THREAD

**Issue by jambulnakal** [ABPindo/indonesianadblockrules#35]
Gan, error nih.. 
Sama kayak yg disini.. [https://adblockplus.org/forum/viewtopic.php?f=10&t=51841](url)

Tapi kalo ABPIndo d disable, normal..

`Error in event handler for (unknown): SyntaxError: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '::content a[href*="http://www.wespoker.com/"], ::content img[title="bandarq online"], ::content img[alt="Advertisement"], ::content a[href*="http://dewapoker.net/"], ::content a[href*="http://pokerqq13.net/"], ::content a[href*="http://www.m88domino.net/"], ::content img[alt="Taruhan Bola"], ::content #popupwindow, ::content a[href*="http://bigextracash.com/"], ::content a[href*="http://masterbaccarat.net/"], ::content a[href*="http://www.fast2bet.com/"], ::content a[href^="http://www.raja111.com"], ::content a[href*="http://angkajitutogel.net/"], ::content a[href*="http://jollywallet.com/"], ::content a[href*="http://www.7nagabet.com/"], ::content a[href^="http://taruhan855.com/"], ::content a[href*="http://ibobandarq.net/"], ::content a[href*="http://tendangsakti.com/"], ::content a[href^="http://cinaqq.com/"], ::content a[href*="http://fast2bet.com/"], ::content a[href*="http://sbo303.com/"], ::content a[href*="http://www.trikqq.com/"], ::content img[title="Agen Togel Online"], ::content .iklanright, ::content a[href*="http://clickadu.com/"], ::content a[href*="http://pastibet.com/"], ::content a[href*="http://www.jayahoki.com/"], ::content img[alt="Judi Online"], ::content #iklan, ::content a[href*="http://bca99.com/"], ::content a[href*="http://m8livepoker.com/"], ::content a[href*="http://www.cbnpoker88.com/"], ::content a[href^="http://www.ladangqq.com"], ::content a[href*="http://agenbola.co/"], ::content a[href*="http://jalanalternatif.co"], ::content a[href*="http://vimaxtrial.com/"], ::content a[href^="http://okebos.top/"], ::content a[href*="http://hokipk.com/"], ::content a[href*="http://sportsmansclub.net/"], ::content a[href^="http://agtwpoker.com/"], ::content a[href*="http://elang13.com/"], ::content a[href*="http://ratubola.com/"], ::content a[href*="http://www.probet99.com/"], ::content img[alt="permainan judi online"], ::content .gbcontent, ::content a[href*="http://btybet.com/"], ::content a[href*="http://obatpembesarpenisklg.id/"], ::content a[href*="http://www.idb365.com/"], ::content img[alt="Agen Judi Online"], ::content #bireklam, ::content a[href*="http://axiobola.com/"], ::content a[href*="http://kontolkuda.co/"], ::content a[href*="http://www.ayomainqq.com/"], ::content a[href^="http://www.bdrqq.com/"], ::content a[href*="http://899cash.net/"], ::content a[href*="http://indopk365.com/"], ::content a[href*="http://u16822.com/"], ::content a[href^="http://ligajudi."], ::content a[href*="http://h8indo.com/"], ::content a[href*="http://sentosa88.net/"], ::content a[href*="http://wwwsgopoker.net"], ::content img[alt="Space Iklan"], ::content a[href*="http://domino168.com/"], ::content a[href*="http://pusat-vimaxasli.com/"], ::content a[href*="http://www.maxbbm.com/"], ::content img[alt="VegasMarket", ::content #tupiklan, ::content a[href*="http://block.s3block.com/"], ::content a[href*="http://mejakiu.com/"], ::content a[href*="http://www.ganoolqq.com/"], ::content a[href^="http://www.seventogel.net"], ::content a[href*="http://asia88bet.com/"], ::content a[href*="http://kamarjudi.com/"], ::content a[href*="http://www.adatogel.com/"], ::content a[href^="http://trikqq.com/"], ::content a[href*="http://idola88.com/"], ::content a[href*="http://togelbos.com/"], ::content a[href^="http://gerhanaqq.com/"], ::content a[href*="http://galaxytoto.com/"], ::content a[href*="http://sbobetid.com/"], ::content a[href*="http://www.unogoal88.com/"], ::content img[title="Judi Bola Online"], ::content .pasangiklan, ::content a[href*="http://daftarbandarpoker.com/"], ::content a[href*="http://pendekarqq.net/"], ::content a[href*="http://www.komopoker.com/"], ::content img[alt="Obat Pembesar Penis"], ::content #iklan_atas, ::content a[href*="http://benderapoker.net/"], ::content a[href*="http://mainidb.com/"], ::content a[href*="http://www.divahoki.com/"], ::content a[href^="http://www.miamiqq.com/"], ::content a[href*="http://agenvimaxindo.org"], ::content a[href*="http://jawaraqq.com/"], ::content a[href*="http://waletjp.com/"], ::content a[href^="http://pulsaqq.com/"], ::content a[href*="http://hoyapoker99.com/"], ::content a[href*="http://starcasino88.com/"], ::content a[href^="http://bdr99.com/"], ::content a[href*="http://en.dompetbola.com/"], ::content a[href*="http://s7bola.com/"], ::content a[href*="http://www.sevenbola.net/"], ::content img[title=" judi bola online"], ::content .iklan728, ::content a[href*="http://cahayapoker.net/"], ::content a[href*="http://opuspoker.com/"], ::content a[href*="http://www.infolinks.com/join-us"], ::content img[alt="Agen QQ"], ::content #fbanner, ::content a[href*="http://bandarbursa.com/"], ::content a[href*="http://liga888.com/"], ::content a[href*="http://www.bla168.com/"], ::content a[href^="http://www.duapoker.com/"], ::content a[href*="http://acmbet.com/"], ::content a[href*="http://interqq.com/"], ::content a[href*="http://venombet.com/"], ::content a[href^="http://mandirimenang.com/"], ::content a[href*="http://hnbwin.com/"], ::content a[href*="http://situsjudi.com/"], ::content a[href*="https://liga77.net/"], ::content a[href*="http://doyankiu.com/"], ::content a[href*="http://qqdomino.net"], ::content a[href*="http://www.pasaranqq.com/"], ::content img[alt="bandar sakong"], ::content .adtext01, ::content a[href*="http://bolaketangkasan.com/"], ::content a[href*="http://muvibet.com/"], ::content a[href*="http://www.hnbwin.com/"], ::content a[href^="https://www.selebtoto.com/"], ::content #Box-Banner-ads, ::content a[href*="http://asianpokerseo.com/"], ::content a[href*="http://ketuapkr.net"], ::content a[href*="http://www.aoecash.com/"], ::content a[href^="http://wongpkr.net/"], ::content a[href*="http://188bet.net/"], ::content a[href*="http://iklanqq.com/"], ::content a[href*="http://topbet899.com/"], ::content a[href^="http://intanqq.net/"], ::content a[href*="http://gebyarbola.company/"], ::content a[href*="http://sbsbet.com/"], ::content a[href*="http://www.waltpoker.com/"], ::content img[title="bandar sakong"], ::content .topadsense, ::content a[href*="http://dewahoki.club/"], ::content a[href*="http://pokerindo99.com/"], ::content a[href*="http://www.luxury138zz.com/"], ::content img[alt="Taruhan Bola Online"], ::content #pbanner, ::content a[href*="http://betwin188.com/"], ::content a[href*="http://master138.net/"], ::content a[href*="http://www.faktavimax.com/"], ::content a[href^="http://www.prediksi855.com/"], ::content a[href*="http://amdbet88.com/"], ::content a[href*="http://jokerqq.me/"], ::content a[href*="http://www.365kiu.com/"], ::content a[href^="http://tangkasq.com/"], ::content a[href*="http://ibcqq.me/"], ::content a[href*="http://tamanqq.com/"], ::content a[href^="http://cendanagaming.com/"], ::content a[href*="http://faktavimax.com/"], ::content a[href*="http://sbbanner.com/"], ::content a[href*="http://www.topbet99.com/"], ::content img[title="Agen Taruhan Bola"], ::content .iklanmini, ::content a[href*="http://cashburners.biz/"], ::content a[href*="http://paperbola.com/"], ::content a[href*="http://www.jarumpk.com/"], ::content img[alt="Judi Online Terpercaya"], ::content #hbanner, ::content a[href*="http://bandartogelsingapore.com/"], ::content a[href*="http://lintasqq.online/"], ::content a[href*="http://www.cacingnaga.com/id"], ::content a[href^="http://www.jasa888.com/"], ::content a[href*="http://agenasia88.com/"], ::content a[href*="http://ivopoker.net/"], ::content a[href*="http://vimaxpills.id/"], ::content a[href^="http://nomorkeluar.com/"], ::content a[href*="http://hokiliga.com/"], ::content a[href*="http://sportsbet.io/"], ::content a[href^="http://abgqq.net"], ::content a[href*="http://earneasycash.info/"], ::content a[href*="http://ramuanobatherball.com/"], ::content a[href*="http://www.prediksisingapore.net/"], ::content img[alt="obatpenisalami"], ::content .forads, ::content a[href*="http://boya13.com/"], ::content a[href*="http://obatjogja.com/"], ::content a[href*="http://www.id-13.com/"], ::content img[alt="Agen Casino Terpercaya"], ::content #adv-placeholder, ::content a[href*="http://astrototo.com/"], ::content a[href*="http://kokibet.com/"], ::content a[href*="http://www.astrototo.com/"], ::content a[href^="http://www.b2poker.net/"], ::content a[href*="http://88indo.com/"], ::content a[href*="http://indomb.com/"], ::content a[href*="http://tujuhbet.com/"], ::content a[href^="http://liga77.net/"], ::content a[href*="http://gopiyopiyo.com/"], ::content a[href*="http://senibola.com/"]{display: none !important;}'.
    at ElemHide.injectSelectors (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:437:24)
    at ElemHide.addSelectors (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:458:12)
    at ext.backgroundPage.sendMessage.response (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:505:14)`

**Comment by gmarcher** [comment]
`https://adblockplus.org/forum/viewtopic.php?f=10&t=51841#p167208`
telah terselesaikan
ngomong-ngomong saya pakai [uBLockOrigin ](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en)dan [AdBlock Plus](https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb) bukan Adblock

**Comment by jambulnakal** [comment]
Bukan, maksudnya kasus nya sama kayak yg di thread itu.. Muncul error yang seperti itu.. Dan kalo saya error nya muncul jika ABPIndo di aktifin.. Saya juga pakai ABP, ga ngeh malah kalau thread itu AB (doang)..

Ini jika tanpa ABPIndo
![abpindo-off](https://user-images.githubusercontent.com/16069337/32640539-5041549a-c5f3-11e7-90cd-40af316b895d.jpg)

Ini jika ABPIndo di aktifkan
![abpindo-on](https://user-images.githubusercontent.com/16069337/32640540-507d2db2-c5f3-11e7-82e0-510c9d8b58dc.jpg)

**Comment by gmarcher** [comment]
tidak ada info lanjut, saya kira suda teratasi
