### ISSUE TITLE
Mislabeled host file

### ISSUE THREAD

**Issue by RicoHeat** [ABPindo/indonesianadblockrules#354]
This subscription is supposed to be hosts 0.0.0.0

https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo_hosts.txt

Please fix. Thanks. 👍

**Comment by gmarcher** [comment]
you can use this
`https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/hosts.txt`

**Comment by RicoHeat** [comment]
@gmarcher That list has a few duplicates. But thanks anyway. 👍

**Comment by gmarcher** [comment]
remove duplicates. Thanks
