### ISSUE TITLE
Iklan Judi dan Lucah

### ISSUE THREAD

**Issue by willjones911** [ABPindo/indonesianadblockrules#364]
## Berikan URL (gunakan kode)
http://104.237.198.197/

## Jelaskan masalah (issue)

Iklan banner di site atas iklan judi dan iklan lucah

screenshot

https://imgur.com/a/z1oH5WE

jika sulit dijelaskan dengan kata-kata tolong sertakan screenshot

## Lingkungan pengujian (beri tanda x)
- [ X] Firefox
- [ ] Chrome
- [X ] uBlock Origin
- [ ] Adblock Plus

uBlock Origin: 1.45.2
Firefox Mobile: 109
filterset (summary): 
  network: 303273
  cosmetic: 158464
  scriptlet: 37186
  html: 860
listset (total-discarded, last-updated): 
  added: 
    adguard-generic: 65739-5798, 17m
    adguard-spyware: 32871-3452, 17m
    adguard-spyware-url: 841-3, 17m
    block-lan: 44-0, 21d.23h.51m
    curben-phishing: 147715-12, 17m
    curben-pup: 187-0, 16m
    adguard-annoyance: 61160-4664, 17m
    adguard-social: 18997-1670, 17m
    fanboy-thirdparty_social: 68-1, 8d.21h.35m
    fanboy-annoyance: 70917-59119, 8d.21h.30m
    fanboy-cookiemonster: 31923-15087, 8d.21h.29m
    fanboy-social: 23396-13721, 4m
    ublock-annoyances: 4868-7, 17m
    dpollock-0: 11390-481, 7d.38m
    IDN-0: 9190-3690, 18m
  default: 
    user-filters: 7-1, never
    ublock-filters: 32167-309, 17m
    ublock-badware: 4011-0, 17m
    ublock-privacy: 286-1, 8d.21h.51m
    ublock-abuse: 76-0, 8d.21h.45m
    ublock-unbreak: 1914-2, 17m
    ublock-quick-fixes: 590-0, 17m
    adguard-mobile: 8217-210, 17m
    easylist: 64799-17990, 17m
    easyprivacy: 30864-12628, 17m
    urlhaus-1: 12940-0, 16m
    plowe-0: 3670-3, 8d.21h.39m
filterset (user): [array of 7 redacted]
trustedset: 
  added: [array of 14 redacted]
  removed: 
    chrome-extension-scheme
    chrome-scheme
switchRuleset: 
  removed: 
    no-csp-reports: * true
modifiedUserSettings: [none]
modifiedHiddenSettings: [none]
supportStats: 
  allReadyAfter: 5835 ms
  maxAssetCacheWait: 7307 ms

**Comment by gmarcher** [comment]
please update your list
