### ISSUE TITLE
gudangmovies (still facing the issue)

### ISSUE THREAD

**Issue by YellowStar11** [ABPindo/indonesianadblockrules#374]
## Berikan URL (gunakan kode)
`gudangmovies21.cfd`

## Jelaskan masalah (issue)
Iklan Judi yg masih terlihat. Masalah belum terselesaikan

## Lingkungan pengujian (beri tanda x)
- [x] Firefox
- [ ] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter
...
![Screenshot_2022-12-22-12-50-59-26_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/98148960/209066671-f42ae669-b5a6-4122-9d7f-c1b51198f380.jpg)

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/61d9d8994f32564c48c04370239b5401b8d77a48
