### ISSUE TITLE
[NSFW] komikdewasa Iklan & tombol iklan 

### ISSUE THREAD

**Issue by YellowStar11** [ABPindo/indonesianadblockrules#377]
## Berikan URL (gunakan kode)
`komikdewasa.art`

## Jelaskan masalah (issue)
Ada Iklan & tombol close iklan di bawah

## Lingkungan pengujian (beri tanda x)
- [x] Brave Browser 

## Usul sintak filter
-
![IMG_20230103_080239](https://user-images.githubusercontent.com/98148960/210288546-ab297cac-781c-43e2-b614-4211288bc209.jpg)

**Comment by gmarcher** [comment]
add `komikdewasa.art##.kln` to your custom filter if you want hide notification
