### ISSUE TITLE
komikcast Iklan

### ISSUE THREAD

**Issue by YellowStar11** [ABPindo/indonesianadblockrules#379]
## Berikan URL (gunakan kode)
`komikcast.site`

## Jelaskan masalah (issue)
Terdapat iklan yang sangat menggangu di situs tersebut 

## Lingkungan pengujian (beri tanda x)
- [x] Brave Browser 

## Usul sintak filter
...
![Screenshot_2023-02-01-19-53-58-07_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/98148960/216209007-94dfc130-0f4a-4d9a-bf87-cf20b3820404.jpg)

**Comment by gmarcher** [comment]
Sudah saya coba dengan brave browser tapi tidak ada masalah disini, iklan terblokir. bisa minta tolong membuatkan PR

**Comment by YellowStar11** [comment]
> Sudah saya coba dengan brave browser tapi tidak ada masalah disini, iklan terblokir. bisa minta tolong membuatkan PR

Iklan sudah tidak muncul lagi..
