### ISSUE TITLE
[NSFW] komikmanhwa.me 

### ISSUE THREAD

**Issue by YellowStar11** [ABPindo/indonesianadblockrules#383]
## Berikan URL (gunakan kode)
`komikmanhwa.me`

## Jelaskan masalah (issue)
Iklan & pop up

## Lingkungan pengujian (beri tanda x)
- [x] Brave Browser Built-in Adblocker 

## Usul sintak filter
..
![Screenshot_2023-02-11-18-23-39-13_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/98148960/218255555-3104113e-d774-45b9-9a27-83ed3eee17d9.jpg)

**Comment by gmarcher** [comment]
apakah brave-adblock bawaan bisa setting filter tersendiri? atau menambahkan filter lain?

**Comment by YellowStar11** [comment]
> apakah brave-adblock bawaan bisa setting filter tersendiri? atau menambahkan filter lain?

Brave adblock bisa menambah filter custom & subscribe filter lain, Layaknya seperti Ublock Origin 
![Screenshot_2023-02-13-13-29-36-76_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/98148960/218386983-5e15e905-8ec6-4c2a-b1a1-aeef55f1c0dd.jpg)
