### ISSUE TITLE
tambahan beberapa domain

### ISSUE THREAD

**Issue by steamboatid** [ABPindo/indonesianadblockrules#390]
## Jelaskan masalah (issue)
Jelaskan secara singkat tentang Pull Request

## Berikan screenshot (pilihan)
jika sulit dijelaskan dengan kata-kata tolong sertakan screenshot

## Lingkungan pengujian (beri tanda x)
- [x] Firefox
- [ ] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter
... jika punya ide, tuliskan sintak filternya
||investopedia.today^
||quantserve.com^
||tapad.com^
||liveperson.net^
||pemsecuy.net^

**Comment by gmarcher** [comment]
||investopedia.today^
Baik, terimakasih domain ini bisa masuk

`||quantserve.com^`
sudah masuk EasyPrivacy

||tapad.com^
saya perlu URL contoh muncul iklannya

`||liveperson.net^`
bukan situs iklan, saya perlu URL contoh muncul iklannya

||pemsecuy.net^
saya perlu URL contoh muncul iklannya

**Comment by steamboatid** [comment]
https://pemsecuy.net/afu.php?zoneid=1146778&var=1146778&rid=ksX-wKK1z8yLZCaWKyzJyw%3D%3D&rhd=false
https://pemsecuy.net/4/5117867/?var=1146778&ab2r=0&prfrev=false&rhd=false
https://pemsecuy.net/4/1146778

https://tag.tapad.com/accounts/39/tags/1mLVdzG/events?data.event_name=pageview&id.maid.value=%22%22&response_type=pixel

https://lptag.liveperson.net/tag/tag.js?site=30187337

**Comment by steamboatid** [comment]
tapad.com dan liveperson.net di-block untuk memmpercepat pencarian domain di godaddy.com

**Comment by gmarcher** [comment]
saya tutup karena sudah fix di easylist, update your filterlist.
