### ISSUE TITLE
Popup open new tab Annoying

### ISSUE THREAD

**Issue by acgl** [ABPindo/indonesianadblockrules#393]
## Berikan URL (gunakan kode)
Movieku.cc dan oploverz.asia

## Jelaskan masalah (issue)
Ketika klik halaman muncul popup tab baru yg mengganggu kadang mengarahkan ke web atau playstore Shopee/lazada

## Berikan screenshot (pilihan)
jika sulit dijelaskan dengan kata-kata tolong sertakan screenshot

## Lingkungan pengujian (beri tanda x)
- [ ] Firefox
- [ ] Chrome
- [ x ] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter
... jika punya ide, tuliskan sintak filternya

**Comment by gmarcher** [comment]
thread saya tutup karena sudah terblokir ublock origin
