### ISSUE TITLE
Terbit21 iklan 

### ISSUE THREAD

**Issue by YellowStar11** [ABPindo/indonesianadblockrules#394]
## Berikan URL (gunakan kode)
`terbit21.cafe`

## Jelaskan masalah (issue)
Terdapat iklan judi 

## Lingkungan pengujian (beri tanda x)
- [x] Brave Browser Built-in Adblock

## Usul sintak filter
-
![Screenshot_2023-03-14-11-09-19-17_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/98148960/224891584-73dcb723-8e2b-45d4-bb82-ef49e2e33831.jpg)

**Comment by YellowStar11** [comment]
@gmarcher Setelah saya mencoba dua baris custom filter Ini di Brave Browser, Banner iklannya hilang. Tolong tambah dua sintaks ini.. Thx
terbit21.cafe##[id*="banner"]
terbit21.cafe##a[target*="blank"] > img

**Comment by gmarcher** [comment]
> @gmarcher Setelah saya mencoba dua baris custom filter Ini di Brave Browser, Banner iklannya hilang. Tolong tambah dua sintaks ini.. Thx terbit21.cafe##[id*="banner"] terbit21.cafe##a[target*="blank"] > img

Terimakasih atas masukannya, saya telah menambahkan filter, tolong update terlebih dahulu ABPindo.
