### ISSUE TITLE
Gudangmovies21 Pop up

### ISSUE THREAD

**Issue by YellowStar11** [ABPindo/indonesianadblockrules#395]
## Berikan URL (gunakan kode)
`gudangmovies21.lol`

## Jelaskan masalah (issue)
Pop up muncul 

## Lingkungan pengujian (beri tanda x)
- [x] Brave Browser Built-in Adblock

## Usul sintak filter
..
![IMG_20230325_205800](https://user-images.githubusercontent.com/98148960/227721733-0243579d-4a1a-476a-8fc9-4c153450a850.jpg)

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/ff7cfbbb5d46ac77dddb432215345c1ff886f7cd

**Comment by YellowStar11** [comment]
> [ff7cfbb](https://github.com/ABPindo/indonesianadblockrules/commit/ff7cfbbb5d46ac77dddb432215345c1ff886f7cd)

@gmarcher Pop Up hanya hilang di Firefox & masih muncul di browser Chromium

**Comment by gmarcher** [comment]
> > [ff7cfbb](https://github.com/ABPindo/indonesianadblockrules/commit/ff7cfbbb5d46ac77dddb432215345c1ff886f7cd)
> 
> @gmarcher Pop Up hanya hilang di Firefox & masih muncul di browser Chromium

di chrome pakai ublock0 atau adblockplus ?

**Comment by YellowStar11** [comment]
> > > [ff7cfbb](https://github.com/ABPindo/indonesianadblockrules/commit/ff7cfbbb5d46ac77dddb432215345c1ff886f7cd)
> > 
> > 
> > @gmarcher Pop Up hanya hilang di Firefox & masih muncul di browser Chromium
> 
> di chrome pakai ublock0 atau adblockplus ?

Masalah sudah terselesaikan setelah saya update filternya. Thx

**Comment by YellowStar11** [comment]
@gmarcher  Pop up kembali muncul setelah domain website berubah. Silahkan mengunjungi link ini: https://gudangmovies21.skin/
