### ISSUE TITLE
dinamani.com

### ISSUE THREAD

**Issue by BlazDT** [ABPindo/indonesianadblockrules#40]
http://www.dinamani.com/tamilnadu/2018/jan/29/%E0%AE%AE%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%B3%E0%AE%BF%E0%AE%A9%E0%AF%8D-%E0%AE%9A%E0%AF%81%E0%AE%AE%E0%AF%88%E0%AE%AF%E0%AF%88-%E0%AE%95%E0%AF%81%E0%AE%B1%E0%AF%88%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AF%81%E0%AE%AE%E0%AF%8D-%E0%AE%A8%E0%AF%8B%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AF%81%E0%AE%9F%E0%AE%A9%E0%AF%8D-%E0%AE%89%E0%AE%AF%E0%AE%B0%E0%AF%8D%E0%AE%A4%E0%AF%8D%E0%AE%A4%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AE%9F%E0%AF%8D%E0%AE%9F-%E0%AE%AA%E0%AF%87%E0%AE%B0%E0%AF%81%E0%AE%A8%E0%AF%8D%E0%AE%A4%E0%AF%81-%E0%AE%95%E0%AE%9F%E0%AF%8D%E0%AE%9F%E0%AE%A3%E0%AE%AE%E0%AF%8D-%E0%AE%95%E0%AF%81%E0%AE%B1%E0%AF%88%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%81-%E0%AE%AE%E0%AF%81%E0%AE%A4%E0%AE%B2%E0%AF%8D%E0%AE%B5%E0%AE%B0%E0%AF%8D-%E0%AE%8E%E0%AE%9F%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AE%BE%E0%AE%9F%E0%AE%BF-%E0%AE%AA-2853444--1.html

Site not displaying correct if ABPindo is active.

https://github.com/AdguardTeam/AdguardFilters/issues/10619

**Comment by gmarcher** [comment]
why using abpindo (indonesian) for indian site? it can lead to miss/false alot

**Comment by BlazDT** [comment]
Still it should be fixed in the filter list. User may visit a lot of different language sites and therefore has it activated.
