### ISSUE TITLE
anichin.top iklan

### ISSUE THREAD

**Issue by richie3011** [ABPindo/indonesianadblockrules#407]
## Berikan URL (gunakan kode)
`https://anichin.top/throne-of-seal-episode-60-subtitle-indonesia/`

## Jelaskan masalah (issue)
Iklan judi & pop up

## Lingkungan pengujian (beri tanda x)
- [ ] Brave Browser Adblock

## Usul sintak filter
![Screenshot_2023-06-30-12-53-42-82_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ABPindo/indonesianadblockrules/assets/98148960/14a7008b-eaa9-4630-a583-608a318a0509)

**Comment by mozzaru** [comment]
Bang masih ada di beberapa device 
Meminta tab baru lalu langsung ke pihak ketiga alis apk ketiga

**Comment by gmarcher** [comment]
terimakasih atas masukannya, 
kamu bisa menambahkan ublock-filters jika tidak mau repot dengan domain yang selalu berganti
`https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt`
![image](https://github.com/ABPindo/indonesianadblockrules/assets/12405001/d3e99151-278e-4ab4-aaa9-c3cfe85ab18b)
