### ISSUE TITLE
tonanmedia.my.id: adblock detection

### ISSUE THREAD

**Issue by T-Baniza** [ABPindo/indonesianadblockrules#409]
## Berikan URL (gunakan kode)
`https://www.tonanmedia.my.id/2023/06/novel-visual-terkenal-dari-key-summer.html?m=1`

## Jelaskan masalah (issue)
browser firefox, ekstensi ublock origin tanpa menggunakan custom filter (default settings + abp indo).
shortlinknya ngedetek ublock, kayanya masalahnya ada di cosmetic filter, pas saya disable cosmetic filtering ga kedetek
NB. saya ceklis 'ignore generic cosmetic filter' di ublock.

## Berikan screenshot (pilihan)
![IMG_20230710_051841](https://github.com/ABPindo/indonesianadblockrules/assets/79722529/eb2cad29-109d-4b44-8530-96ab6b2c41a5)

## Lingkungan pengujian (beri tanda x)
- [X] Firefox
- [X] uBlock Origin

**Comment by partingscientist** [comment]
Do you have the original link?

**Comment by T-Baniza** [comment]
> Do you have the original link?

nevermind. after i parse

**Comment by T-Baniza** [comment]
> Do you have the original link?

never mind. after i parse and enforce the filters and using ubo annoyance, adguard popup overlays, it can pass through the shortlink. thanks before

here's the original link if you want to check it out `https://extonan.id/watashi-no-shiawase-na-kekkon-episode-01/` 1080p [Gudang Mirror]

**Comment by gmarcher** [comment]
https://github.com/uBlockOrigin/uAssets/issues/18580
