### ISSUE TITLE
Remove the snippet filter file (`snippet_adblockplus.txt`)

### ISSUE THREAD

**Issue by partingscientist** [ABPindo/indonesianadblockrules#413]
According to [ABP documentation](https://help.adblockplus.org/hc/en-us/articles/1500002338501),

> For security reasons, snippet filters can only be added to a user's custom filters list or in the [ABP Anti-Circumvention Filter List](https://github.com/abp-filters/abp-filters-anti-cv), the latter being vetted and reviewed.

With this in mind, and unless I'm missing anything, I think this file (https://github.com/ABPindo/indonesianadblockrules/blob/master/src/advert/snippet_adblockplus.txt) can be deleted because ABPIndo cannot introduce any snippet filter(s) to users anyway.

What do you think?

**Comment by gmarcher** [comment]
yes, same with scriptlet ublock.

**Comment by partingscientist** [comment]
I would lean towards keeping `scriptlet_ublock.txt`, so that the idea of maintaining such list will not be off the list, for now. If you don't mind, I will create a PR for the issue title.
