### ISSUE TITLE
gudangmovies21 pop up

### ISSUE THREAD

**Issue by ChowMein47** [ABPindo/indonesianadblockrules#414]
## Berikan URL (gunakan kode)
`gudangmovies21.skin`

## Jelaskan masalah (issue)
Pop up muncul. Juga muncul di brave Browser 

## Lingkungan pengujian (beri tanda x)
- [x] Firefox
- [ ] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter
![Screenshot_2023-07-15-08-04-06-36_3aea4af51f236e4932235fdada7d1643](https://github.com/ABPindo/indonesianadblockrules/assets/98148960/7bffb322-ca6a-41af-a71a-c113f4366379)

**Comment by partingscientist** [comment]
Does this work?

```adblock
gudangmovies21.skin##+js(nostif, sgpb)
```

**Comment by partingscientist** [comment]
Alternatively, can you remove that previous filter and test these instead?

```adblock
gudangmovies21.skin###sgpb-popup-dialog-main-div-wrapper
gudangmovies21.skin##.sgpb-popup-overlay
```

These have a lesser chance of breaking the site.

**Comment by partingscientist** [comment]
I cannot reproduce. Have you updated your filter list (even though nothing has changed since a month ago)? Perhaps you have forgotten to enable your regional filters?
