### ISSUE TITLE
layardrama21 : ads & pop up

### ISSUE THREAD

**Issue by richie3011** [ABPindo/indonesianadblockrules#421]
## Berikan URL (gunakan kode)
`https://layardrama21.rest/`

## Jelaskan masalah (issue)
Iklan judi & pop up

## Berikan screenshot (pilihan)
![Screenshot_2023-07-20-08-43-36-01_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ABPindo/indonesianadblockrules/assets/98148960/a935b92f-0e38-4a18-a6e6-0548cb802642)
![Screenshot_2023-07-20-08-42-06-16_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ABPindo/indonesianadblockrules/assets/98148960/f6c6ab12-df76-4a7f-9953-e5bf10232111)

## Lingkungan pengujian (beri tanda x)
- [x] Brave Browser Built in Adblock

## Usul sintak filter
-

**Comment by partingscientist** [comment]
In case you did not know, you can auto close issues using [keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue).
