### ISSUE TITLE
komikcast.io iklan

### ISSUE THREAD

**Issue by richie3011** [ABPindo/indonesianadblockrules#425]
## Berikan URL (gunakan kode)
`https://komikcast.io/`

## Jelaskan masalah (issue)
Iklan judi

## Berikan screenshot (pilihan)
![Screenshot_2023-07-23-10-45-56-15_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ABPindo/indonesianadblockrules/assets/98148960/c0903c00-a8f6-4d7d-91b8-22b97dd085b3)

## Lingkungan pengujian (beri tanda x)
- [x] Brave Browser Built in Adblock 

## Usul sintak filter
-

**Comment by partingscientist** [comment]
Can you update your filter list? I cannot reproduce the issue.

**Comment by gmarcher** [comment]
803dd46d6276706d215d5c2043c47c18e7026840

yep update your filter list

**Comment by partingscientist** [comment]
You can add `komikcast.io##.kln` to your filter list for now.

**Comment by gmarcher** [comment]
294f04b9ba9e24ddd0af8b8e5d278bf9d1ffe679
