### ISSUE TITLE
doroni.me detect adblock

### ISSUE THREAD

**Issue by sibernaut** [ABPindo/indonesianadblockrules#427]
## Berikan URL (gunakan kode)
`https://doroni.me/anime/reinkarnasi-pengangguran-musim-kedua/episode-02`

## Jelaskan masalah (issue)
download link diganti box "Matikan AdBlock untuk melihat link download!"

### Seharusnya
![Screenshot 2023-07-23 222835](https://github.com/ABPindo/indonesianadblockrules/assets/64172441/152f982c-647e-47e5-94aa-a18b3a09f80d)
### Terdeteksi
![Screenshot 2023-07-23 222739](https://github.com/ABPindo/indonesianadblockrules/assets/64172441/f8c88323-42e7-4e56-8754-3545a4975766)

## Lingkungan pengujian (beri tanda x)
- [x] Firefox
- [ ] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter
... jika punya ide, tuliskan sintak filternya

**Comment by partingscientist** [comment]
Does this work?
`doroni.me##+js(acs, getComputedStyle, , cpm)`

**Comment by sibernaut** [comment]
Yes, it's work.
