### ISSUE TITLE
Hosts file untuk adaway, blokada, dsb

### ISSUE THREAD

**Issue by staclarapa** [ABPindo/indonesianadblockrules#43]
pas coba diadd di adaway, ga detect nih hostnya tulisannya not available.

**Comment by dikiaap** [comment]
Relevant: #29 

Saya generate dari nawala, tapi cuma ada yang scam dan judi

https://gist.githubusercontent.com/dikiaap/e3a2d3545d762cad76761283447608be/raw/2891785d70982acae63e014385af3f134419287b/daftar-situs-scam-dan-judi.txt

**Comment by gmarcher** [comment]
adaway masih adblockplus compatible tidak? @dikiaap

**Comment by dikiaap** [comment]
Belum pernah nyoba. Kurang tahu saya kalau AdAway bisa generate format rules dari filter-filter kayak gini.
Saya nunggu ada yang buatin script buat generate filter-filter sini ke /etc/hosts. :smile:

**Comment by gmarcher** [comment]
kalau mau dipakai di AdWay mungkin cuma ini saja yang digenerate
`abpindo_adservers.txt` (isinya jelas domain iklan)
`abpindo_annoyance.txt` (isinya iklan judi)
biar tidak banyak kesalahan

**Comment by 3xploiton3** [comment]
ABPindo di adaway bisa pakai ini

> https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/converter/filter/easylist-abpindo.txt

**Comment by akhyarrh** [comment]
> ABPindo di adaway bisa pakai ini
> 
> > https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/converter/filter/easylist-abpindo.txt

update link:
https://github.com/EnergizedProtection/block/raw/master/assets/converter/filter/abpindo.txt

**Comment by abesty** [comment]
@akhyarrh not available anymore 🙁

**Comment by akhyarrh** [comment]
> https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/converter/filter/abpindo.txt

Disitu masih ada

**Comment by dederaditya** [comment]
not found ada yang punya backupnya?

**Comment by gmarcher** [comment]
> 
> 
> not found ada yang punya backupnya?
Pindah kesini
`https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/sources/filter/abpindo.txt`

**Comment by zputnyq** [comment]
> > not found ada yang punya backupnya?
> 
> Host ABPindo sudah ada maintener nya dan pindah kesini:
> `https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/sources/filter/abpindo.txt`

Sdh "404 - not found" skg

**Comment by akhyarrh** [comment]
Sebenarnya EnergizedProtection ada memberi link raw nya, tapi mereka menggabung semua host regional dari berbagai negara

**Comment by gmarcher** [comment]
Pindah ke sini
https://github.com/ABPindo/indonesianadblockrules/issues/186
