### ISSUE TITLE
Filter Accuracy check

### ISSUE THREAD

**Issue by CbumDino** [ABPindo/indonesianadblockrules#449]
## Jelaskan masalah (issue)

Hello, i would like to confirm if the following filters are somehow accurate, since it's not common to find `example.^` filters. 
Are they intended to be written in that way ? If so, do you have few examples were i can try it out ? 

Thank you in advance, have a wonderful day.
## Usul sintak filter

Filter examples:
```
||agungqiu.^$third-party
||bet2link.^$third-party
||bmwpoker.^$popup
||cmcpoker.^$third-party
||obatpembesarpenisklg.^$popup
@@||updatetribun.^$generichide
```

**Comment by gmarcher** [comment]
Wonderful 
yes you right, it's not mark as invalid by Adblock/AdGuard/uBlock filters grammar, so i missed it
