### ISSUE TITLE
fastnet tracking

### ISSUE THREAD

**Issue by dennyhalim** [ABPindo/indonesianadblockrules#5]
fastnet mengganti ip semua domain yg diblokir dan menampilkan:
domainterblokir/internetsehatdanamanfastnet.html
dengan gambar domainterblokir/internetsehat_fm.png
sehingga memungkinkan utk tracking user yg mengakses situs tsb.

**Comment by gmarcher** [comment]
Seharusnya sudah, tolong dicek lagi
