### ISSUE TITLE
shinigamitoon.id

### ISSUE THREAD

**Issue by ChowMein47** [ABPindo/indonesianadblockrules#554]
## Berikan URL (gunakan kode)
`https://shinigamitoon.id/`

## Jelaskan masalah (issue)
Ads

## Berikan screenshot (pilihan)
![Screenshot_2024-06-07-11-08-12-48_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ABPindo/indonesianadblockrules/assets/98148960/298e031e-fbb9-4840-abc5-0f4fbfe6f01e)
![Screenshot_2024-06-07-11-08-32-71_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/ABPindo/indonesianadblockrules/assets/98148960/0613db62-4f97-41e6-9165-858c5e521ac4)

## Lingkungan pengujian (beri tanda x)
- [x] Brave's adblock rust

## Usul sintak filter
.

**Comment by gmarcher** [comment]
95f15ddd4e6daa541d8f6c853537508ec5898119
