### ISSUE TITLE
http://awsubs.co/

### ISSUE THREAD

**Issue by What-Zit-Tooya** [ABPindo/indonesianadblockrules#56]
Ketika mengunjungi situs http://awsubs.co/, ada bayang-bayang hitam yang mucnul, dan ane gak bs klik lik di situs tsb. Tapi setelah ane matiakn filter IDN: ABPindo, situsnya bs diakses dan tidak ada bayang-bayang hitam & ane bs click link-link di situ, mohon perbaikan

https://github.com/uBlockOrigin/uAssets/issues/4005

**Comment by gmarcher** [comment]
pakai speedy atau indihome ya? dari sini tidak ada masalah baik chrome atau firefox, semua pakai ublock

**Comment by idoenk** [comment]
atau saranin yg punya web pakein ssl (https), eg. let's encrypt.. he//
minimalisir isu webnya diinjek provider. :)

**Comment by exodius48** [comment]
@gmarcher pakek indihome ini, tp skrg udh aman , setelah update filter di ublock

@idoenk ane gak berani ngomong ke yg punya web, ntr malah kena semprot. hahaha
