### ISSUE TITLE
samehadaku.email

### ISSUE THREAD

**Issue by 3xploiton3** [ABPindo/indonesianadblockrules#567]
## Berikan URL (gunakan kode)
samehadaku.email

## Berikan screenshot (pilihan)
![image](https://github.com/user-attachments/assets/d9e23d7c-198c-4cb4-9f96-b6f9f7887323)

## Lingkungan pengujian (beri tanda x)
Chrome

ads

**Comment by gmarcher** [comment]
ublock origin masih bisa digunakan di chrome, kenapa menggunakan ublock origin lite?
