### ISSUE TITLE
judi online

### ISSUE THREAD

**Issue by alsyundawy** [ABPindo/indonesianadblockrules#577]
berikut listnya

https://github.com/alsyundawy/TrustPositif/raw/main/gambling_indonesia.txt

**Comment by gmarcher** [comment]
Terimakasih atas reponya, sangat bagus, seharusnya sejak dulu kominfo punya seperti ini biar terang benderang. Tolong reponya bisa terus diupdate, jadi kami punya daftar acuan.

#186
