### ISSUE TITLE
RPZ & UNBOUND FORMAT

### ISSUE THREAD

**Issue by alsyundawy** [ABPindo/indonesianadblockrules#578]
please support rpz and unbound format

**RPZ Format**

```
$TTL 300
@ SOA localhost. root.localhost. 1715037180 43200 3600 259200 300
  NS  localhost.

domain.tld CNAME .
*.domain.tld CNAME .
```

**Unbound Format**

```
server:
local-zone: "domain.tld." always_nxdomain
```

**Comment by gmarcher** [comment]
Maksudnya ini?
`https://github.com/ABPindo/indonesianadblockrules/blob/master/subscriptions/rpz.txt`

**Comment by alsyundawy** [comment]
apakah sesuai dengan format rpz yg saya buatkan diatas diatas? rpz mesti wildard dan mesti ada soa

dan tambahkan juga support format untuk unbound

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/281157af35337e70bdbed55b6c126d22a9d52483

terimakasih atas kesabarannya, semoga sesuai harapan masa depan
