### ISSUE TITLE
https://blurayufr.cam/

### ISSUE THREAD

**Issue by psiponp** [ABPindo/indonesianadblockrules#597]
## Berikan URL (gunakan kode)
`blurayufr.cam'

## Jelaskan masalah (issue)
'ad block terdeteksi situs memunculkan jendela pop up untuk mengahalangi penggunaan halaman'

## Berikan screenshot (pilihan)
jika sulit dijelaskan dengan kata-kata tolong sertakan screenshot
![Screenshot_2024-10-16-18-06-08-623_com kiwibrowser browser](https://github.com/user-attachments/assets/89eb180a-bf7e-4770-afce-69ea55cc715f)

## Lingkungan pengujian (beri tanda x)
- [ ] Firefox
- [x] Chrome
- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter (tulis kode)
`jika punya ide, tuliskan sintak filternya`

**Comment by gmarcher** [comment]
https://github.com/uBlockOrigin/uAssets/issues/25711
