### ISSUE TITLE
cosmic1.co

### ISSUE THREAD

**Issue by ChowMein47** [ABPindo/indonesianadblockrules#602]
## Berikan URL (gunakan kode)
`https://cosmic1.co/`

## Jelaskan masalah (issue)
Iklan judi

## Berikan screenshot (pilihan)
![Screenshot_2024-11-03-11-52-49-08_e4424258c8b8649f6e67d283a50a2cbc](https://github.com/user-attachments/assets/12f86863-02f6-4467-afa5-142278c376e4)

## Lingkungan pengujian (beri tanda x pada braket)
- [ ] Brave Browser Built In Adblock

## Usul sintak filter (tulis kode)
none

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/c17a3ad56bb0222ce37bfcda8b60ff5cc1cc0ca2 Thanks for your patience
