### ISSUE TITLE
Domains wildcards filters in Adblock Plus

### ISSUE THREAD

**Issue by smed79** [ABPindo/indonesianadblockrules#61]
Hi,

do you know that your domains wildcards filters are not working and disabled in **Adblock Plus** ?

try

```
lanik.us,adblockplus.org##a[id$="logo"]
```
then
```
lanik.us,adblockplus.*##a[id$="logo"]
```

**Comment by gmarcher** [comment]
not sure, until trying ABP for firefox and "it's really not working". thanks for reminder

**Comment by smed79** [comment]
I found an ABP issue which request to implement support for domain wildcards https://issues.adblockplus.org/ticket/6773
