### ISSUE TITLE
Samehadaku website page content missing

### ISSUE THREAD

**Issue by argosaroso** [ABPindo/indonesianadblockrules#612]
## Berikan URL (gunakan kode)
`[samehadaku.email]`

## Jelaskan masalah (issue)
Konten dalam page hilang ketika memblock menggunakan kode tertentu.

Dari analisa saya konten page akan rusak kalau menggunakan filter seperti ini
`||samehadaku.email/wp-content/uploads/2024/*.gif$image`

Tapi yang menarik jika anda telusuri lebih lanjut yang membuat error adalah gif di bulan 08

`||samehadaku.email/wp-content/uploads/2024/01/*.gif$image
||samehadaku.email/wp-content/uploads/2024/02/*.gif$image
||samehadaku.email/wp-content/uploads/2024/03/*.gif$image
||samehadaku.email/wp-content/uploads/2024/04/*.gif$image
||samehadaku.email/wp-content/uploads/2024/05/*.gif$image
||samehadaku.email/wp-content/uploads/2024/06/*.gif$image
||samehadaku.email/wp-content/uploads/2024/07/*.gif$image
||samehadaku.email/wp-content/uploads/2024/09/*.gif$image
||samehadaku.email/wp-content/uploads/2024/10/*.gif$image
||samehadaku.email/wp-content/uploads/2024/11/*.gif$image
||samehadaku.email/wp-content/uploads/2024/12/*.gif$image`

Jika menjalankan seperti ini tidak ada masalah tapi masih ada iklan yang muncul

## Berikan screenshot (pilihan)
Sebelum
![Screenshot 2024-11-27 131526](https://github.com/user-attachments/assets/f15b4fae-fb24-48ba-952d-57682d75dc4a)
Sesudah apply filter
![Screenshot 2024-11-27 131633](https://github.com/user-attachments/assets/08d0b64a-8bfd-4b06-a1c9-05f09a0f752a)
## Lingkungan pengujian (beri tanda x pada braket)
- [ ] Firefox
- [x] Chrome

- [x] uBlock Origin
- [ ] Adblock Plus

## Usul sintak filter (tulis kode)
Saya tidak tahu rekomendasi kode, mohon bantuannya

**Comment by gmarcher** [comment]
terimakasih atas issue nya, update akan segera masuk

**Comment by argosaroso** [comment]
Thanks bantuannya
