### ISSUE TITLE
movieku: ads & link judol

### ISSUE THREAD

**Issue by kemalhiero** [ABPindo/indonesianadblockrules#622]
## Berikan URL (gunakan kode)
`https://movieku.ink/`
`https://movieku.ink/rogue-one-a-star-wars-story-2016/`

## Jelaskan masalah (issue)
iklan judol, ada di halaman utama dan halaman detail film. 
website judol di iklannya juga bisa diakses
- `https://kstcuan.org/`
- `https://d3w4pok3rtop.org/`
- `https://adobet88qq.com/`
- `https://boxcina.cyou/`

## Berikan screenshot (pilihan)
![Cuplikan layar 2024-12-14 083705](https://github.com/user-attachments/assets/7f34b2af-225f-4f3f-beef-88aa052ddf3a)
![Cuplikan layar 2024-12-14 084025](https://github.com/user-attachments/assets/7ed9609f-dce3-465e-b0d8-db4d8ca9be2d)
![image](https://github.com/user-attachments/assets/0f0e300c-f073-475c-8ffd-5cda6092e172)

## Lingkungan pengujian (beri tanda x pada braket)
- [ ] Firefox
- [x] Chrome

- [x] uBlock Origin (uBO Lite)
- [ ] Adblock Plus

## Usul sintak filter (tulis kode)
- -

**Comment by male514** [comment]
ada iklan judol baru @gmarcher 

<img width="1495" height="842" alt="Image" src="https://github.com/user-attachments/assets/fe2d0765-e70e-466e-9cd6-1cd2555572f8" />
