### ISSUE TITLE
Domain spoofing: dunlop.id 

### ISSUE THREAD

**Issue by onmyouji** [ABPindo/indonesianadblockrules#623]
## Berikan URL (gunakan kode)
`dunlop.id`

## Jelaskan masalah (issue)
Fake domain yang meniru domain situs ban Dunlop. Situs resmi ban Dunlop adalah `www.dunlop.co.id`.
Domain `dunlop.id` akan meneruskan (redirect) user ke situs judi online.

## Lingkungan pengujian (beri tanda x pada braket)
- [x] Firefox
- [ ] Chrome

- [x] uBlock Origin
- [ ] Adblock Plus

**Comment by gmarcher** [comment]
terimakasih atas masukannya, karena tidak ada contoh site nya langsung, saya tulis pihak ketiga dan popup, akan lebih mantab jika menggunakan dns yang support blokir judi.
