### ISSUE TITLE
xxiku.com: ads

### ISSUE THREAD

**Issue by 3xploiton3** [ABPindo/indonesianadblockrules#624]
![image](https://github.com/user-attachments/assets/7139082c-70d8-43b6-8c8c-146567825a52)

https://xxiku.com/sisu-2023/

uBOL Lite

**Comment by 3xploiton3** [comment]
Pop up

![image](https://github.com/user-attachments/assets/86eb96e9-3b03-4687-a94a-f777d70acd1d)

**Comment by gmarcher** [comment]
karena internasional masuknya easylist ya 
![image](https://github.com/user-attachments/assets/68d5144e-facc-408a-8a59-1c3c768f47f8)
