### ISSUE TITLE
Direktori situs judi

### ISSUE THREAD

**Issue by 3xploiton3** [ABPindo/indonesianadblockrules#67]
http://onetpedia.net/

isinya web2 judi, banyak yang belum terblock

**Comment by gmarcher** [comment]
Wow banyak banget, ada listnya tdk tu. Saya pakai dns nawala jadi kebanyakan sudah terblokir, jd yang diblokir yang terlewat nawala saja dan jelas tampil di situs-situs berbahasa indonesia. 
Kalau ttp mau menambah tlg dicek satu-satu domainnya aktif tidak, pakai script validatehost.py atau yang lain

**Comment by 3xploiton3** [comment]
Saya pakai dns crypt cloudflare,
Klo pakai nawala banyak web penting yg terblock, jd gak tau websitenya mati atau ke block dns, klo pakai dns cloudflare semua kelihatan

Saya pakai filter energized ultimate, regional dan xtreme, jadi tau dns judi yg blm terblock

Klo dr nawala apa bisa di generate jadi filter ke ublock?

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/issues/43 statusnya blm close, harusnya bisa, cuma tidak ada ilmunya. Judinya cukup yang muncul di situs berbahasa indonesia saja, karena biasanya domain seperti ini sering mati/ganti. Nanti malah jadi filter domain mati kalau semua ditambahkan.

**Comment by 3xploiton3** [comment]
Kalau domain mati bisa di cek pakai tool validate host, atau  semacamnya
bila sudah mati masukkan ke list dead link sewaktu-waktu muncul kembali bisa di ambil, bisa juga buat dokumentasi

**Comment by gmarcher** [comment]
> bila sudah mati masukkan ke list dead link sewaktu-waktu muncul kembali bisa di ambil, bisa juga buat dokumentasi
nah itulah fungsi comment pas PR, saya sering kelewatan karena PR nya sekaligus

**Comment by maildian** [comment]
> 
> 
> http://onetpedia.net/
> 
> isinya web2 judi, banyak yang belum terblock

webnya udah mati
