### ISSUE TITLE
add filter.

### ISSUE THREAD

**Issue by Reoldyk** [ABPindo/indonesianadblockrules#7]
apakah bisa menambahkan filter ini ke ABPindo?
==================
wardhanime.net,www.oploverz.net###btm_banner
mangacanblog.com,www.mangacanblog.com###close > a
uptobox.com##.qycxmejb-bg
uptobox.com###zprhbjew
www.duniaku.net###banner-popup-desktop
www.mangamint.com###sliding-popup

**Comment by gmarcher** [comment]
contoh link akan sangat membantu

**Comment by Reoldyk** [comment]
terimakasih atas balasannya.
itu filter yg aku buat, mungkin bisa dimasukkan ke daftar filter ABPindo.

kalo mau link, bisa coba ini.
http://mangaku.web.id/magi-the-labyrinth-of-magic-chapter-297-kemungkinan-berhasil/
http://www.mangacanblog.com/baca-komik-magi-297-298-bahasa-indonesia-magi-297-terbaru-1.html
http://wardhanime.net/
http://www.oploverz.net/
www.mangamint.com

**Comment by gmarcher** [comment]
makasih laporannya, silahkan diupdate

**Comment by Reoldyk** [comment]
terimakasih sudah ditambahkan.

dan muncul masalah baru, 2 hari yg lalu mangacan masang anti adblock.
apakah bisa melakukan sesuatu untuk masalah ini?
sample link = http://www.mangacanblog.com/baca-komik-magi-297-298-bahasa-indonesia-magi-297-terbaru-1.html
screenshot = http://s16.postimg.org/64cflfs8l/Untitled.png

**Comment by Reoldyk** [comment]
muncul banner baru juga,
www.mangacanblog.com###btm_banner

**Comment by gmarcher** [comment]
sudah coba [reek](https://greasyfork.org/en/scripts/735-anti-adblock-killer-reek) ? dari sini tidak kelihatan iklannya

**Comment by Reoldyk** [comment]
udah nyoba make  script + filter dari reek, tapi masih muncul anti adblock.
SS= http://s16.postimg.org/64cflfs8l/Untitled.png

aku nyoba nambahin filter ini, anti adblock-nya ilang.
@@.jpg#$domain=www.mangacanblog.com
@@||www.mangacanblog.com^$elemhide

**Comment by gmarcher** [comment]
silahkan update list lagi

**Comment by Reoldyk** [comment]
terimakasih sudah diupdate.

**Comment by Reoldyk** [comment]
ternyata tanpa filter ini, gak muncul anti adblocknya,
@@.jpg#$domain=www.mangacanblog.com
@@||www.mangacanblog.com^$elemhide

masalah yg dulu muncul browserku krn gak aku update browser ke yg versi terbaru.
