### ISSUE TITLE
How make rule with 1 word for all filter

### ISSUE THREAD

**Issue by 3xploiton3** [ABPindo/indonesianadblockrules#74]
Bagaimana caranya membuat filter otomatis, 1 kata bisa generate banyak filter,
misal pengin block domain dengan kata `dewapoker`
langsung otomatis generate seperti di bawah ini masuk ke kategori doc masing-masing

||dewapoker.$popup,third-party
##a[href^="http://dewapoker."]
/dewapoker.

apakah bisa dikerjakan?

**Comment by gmarcher** [comment]
bisa sekali, cuma sy yang tidak bisa
