### ISSUE TITLE
semprot.com filter change

### ISSUE THREAD

**Issue by cubakcabak** [ABPindo/indonesianadblockrules#8]
semprot.com##.cintasemprot_sq
semprot.com##.haphapsemprot_floating_banner_top
semprot.com##.haphapsemprot_floating_banner_bottom
semprot.com##.haphapsemprot_h
semprot.com###haphapsemprot_side_left
semprot.com###haphapsemprot_side_right
semprot.com###yayal_nav
semprot.com###yayaya_footer

**Comment by gmarcher** [comment]
force update

**Comment by cubakcabak** [comment]
done. works wonderfully.

thank you.
