### ISSUE TITLE
anoboy.org

### ISSUE THREAD

**Issue by 3xploiton3** [ABPindo/indonesianadblockrules#81]
![image](https://user-images.githubusercontent.com/19517680/55125119-4c81b500-513b-11e9-9995-1b6aa2ea3d75.png)

block banner judi bola

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/commit/eadc1b0cf2aab3a5839be54ed6c47c6e46cd437a#diff-56265cd77e3d03f8940bef74911b7b34
