### ISSUE TITLE
Add note about Manifest v3

### ISSUE THREAD

**Issue by DandelionSprout** [ABPindo/indonesianadblockrules#86]
Greetings, Dandelion Sprout here again.

So it seems that the Chromium team [has decided to follow through with their war on adblockers](https://9to5google.com/2019/05/29/chrome-ad-blocking-enterprise-manifest-v3/), by having a laughably small current rule limit of 35,000 and by seemingly removing most of the more advanced syntaxes that recent adblocker versions can use from October-ish onwards. So tonight I've decided to venture a bit around on the GitHub issue trackers of various lists that are included in adblockers, and get them to publicly take a stance against Manifest v3, in order to educate laymen and to establish *some* kind of pressure on the Chromium team.

I notice that this repo's Readme is in Indonesian only, and since I don't speak Indonesian nor Malaysian at all, you'd presumably have to translate the note template that I'm slowly spreading around on GitHub (Written in `.md` format):

`<b>IMPORTANT NOTE FOR CHROMIUM-BROWSER USERS:</b> Our lists does not, can not, and will never ever support Manifest v3, due to its laughably short rule limit which will most likely prevent you from loading this list alongside most other lists. Issue reports for Manifest v3-based extension versions will not be accepted, and if you do submit one, you would be asked to use an alternate web browser or web browser version instead.`

**Comment by DandelionSprout** [comment]
Amendment:

Apparently it's not set in stone when v3 will be introduced to non-nightly users (I had previously assumed sometime in August), I had mistaken Chromium Canary for Chrome Canary, and smed79 (who seems to me to be an authority on EasyList and ABP stuff) believes that list writers should be neutral when it comes to things like these.

I do however think this is worth at least thinking about or to keep in mind for the future.

**Comment by gmarcher** [comment]
Thanks for the information, i will add it for next update.
sorry for delay
