### ISSUE TITLE
block iklan kuyhaa.me

### ISSUE THREAD

**Issue by 3xploiton3** [ABPindo/indonesianadblockrules#88]
tolong block tampilan pop up ketika klik di pencarian

https://www.kuyhaa.me/

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/60451181-b4253000-9c55-11e9-86f9-cc500a81f823.png)

**Comment by gmarcher** [comment]
Kamu bisa juga melakukan PR, penempatan filternya bisa dilihat [di wiki](https://github.com/ABPindo/indonesianadblockrules/wiki/Penempatan-daftar-iklan)
