### ISSUE TITLE
Tolong sediakan juga format untuk /etc/hosts

### ISSUE THREAD

**Issue by hillz2** [ABPindo/indonesianadblockrules#89]
Halo,

Saya ingin menggunakan ABPindo di router openwrt saya yang berbasis linux, format /etc/hosts biasanya begini:

```
127.0.0.1 localhost
127.0.0.1 localhost.localdomain
127.0.0.1 local
255.255.255.255 broadcasthost
0.0.0.0 006a039c957c142bb.com
0.0.0.0 006.free-counter.co.uk
0.0.0.0 0073dd485d46d930dd9.co
```

Bisa tolong request format yang spt itu untuk di masukkan ke file /etc/hosts? thx

**Comment by gmarcher** [comment]
https://github.com/ABPindo/indonesianadblockrules/issues/43#issuecomment-453604088

**Comment by hillz2** [comment]
Thx
