### ISSUE TITLE
Add Filter

### ISSUE THREAD

**Issue by Reoldyk** [ABPindo/indonesianadblockrules#9]
anisubsia.com###btm_banner

dan tolong block ini juga, http://s8.postimg.org/b7boloq2t/Untitled.png

**Comment by gmarcher** [comment]
update, yang di ss dari sini tidak masalah

**Comment by Reoldyk** [comment]
terima kasih sudah di tambahkan,
dan yg di SS sudah hilang juga skrng.

**Comment by Reoldyk** [comment]
tambah ini min
www.mangakita.net###btm_banner
www.mangacanblog.com###popup

apa aku harus buka trit baru lagi saja, gak perlu komen disini.

**Comment by gmarcher** [comment]
makasih updatenya, iya satu web satu laporan saja biar mudah menelusurinya. ini saya lock
