### ISSUE TITLE
Q: apakah bisa memblokir 3d party script safelink lain

### ISSUE THREAD

**Issue by RaveN0X87** [ABPindo/indonesianadblockrules#92]
![Annotation 2019-08-22 000449](https://user-images.githubusercontent.com/39649317/63452467-8ea3ee00-c470-11e9-92a7-f515bae1b7e8.png)

contohnya seperti : 
https://www.adtival.network/ 
https://adsafelink.net/
https://safelinkblogger.com/
dll

biar seperti safelinku yg langsung menuju filehosting
![Untitled](https://user-images.githubusercontent.com/39649317/63452841-7d0f1600-c471-11e9-8457-e6c6d81341af.png)

klo bisa tolong ditambahkan filter untuk memblokir 3d party script safelink lain yg menjengkelkan
terima kasih

**Comment by 3xploiton3** [comment]
Klo di block gak bisa masuk ke link hosting,
Klo kasus seperti ini saya pakai bypass script, adsbypasser

**Comment by RaveN0X87** [comment]
iya saya sudah pke universal bypass tp ada beberapa safelink terutama di web" indo yg blum tersupport
contohnya :
https://movieku.org/brightburn-subtitle-indonesia/
https://drivenime.com/yami-shibai-subtitle-indonesia-batch/
https://hananime.com/dokter-stone/
dll

**Comment by 3xploiton3** [comment]
Universal bypass juga bisa, kadang saya pakai ini juga, tetapi lebih utama
yg adsbypasser,

Klo belum support bisa request ke github issues universal bypass,

**Comment by RaveN0X87** [comment]
uda request sih 3bulan yg lalu tp katanya banyak komponen backend gtu ga ngerti jg sih soalnya bukan dibidangnya jdi katanya msh belum bisa difix dlm waktu dekat.
klo adsbypasser ga ada crowd bypassnya kebanyakan shortener yg template adlinkfly msh belum tersupport dan dev nya jg skrng kurang aktif ga kyk dolo mungkin sibuk kerjaan jd klo request shortener baru kemungkinan ditambahkanya lama
