### ISSUE TITLE
iklan judi belum terblokir

### ISSUE THREAD

**Issue by KagaKouko99** [ABPindo/indonesianadblockrules#93]
https://idkomik.com/

sama nanya bedanya filter ini sama yg ABPIndo+easylist apa ?
makasih

**Comment by gmarcher** [comment]
> sama nanya bedanya filter ini sama yg ABPIndo+easylist apa ?
sama saja, kalau sudah terpasang ABPIndo+easylist tidak perlu manual pasang ABPindo atau easylist secara terpisah.
Kalau bahasa browsernya sudah indonesia otomatis nanti langsung terisi ABPIndo+easylist. tapi kalau bahasa browsernya selain indonesia (english) perlu ditambah manual ABPindo.
