### ISSUE TITLE
woof.tube - adblock detection

### ISSUE THREAD

**Issue by BlazDT** [ABPindo/indonesianadblockrules#94]
https://woof.tube/stream/89qHbXqdjfL

Adblock detection, fix:

woof.tube#@#.adsbox

https://github.com/AdguardTeam/AdguardFilters/issues/39405

**Comment by gmarcher** [comment]
it's italian site, so EasyList Italy

**Comment by BlazDT** [comment]
It is not an Italian site, only the subtitles in the video are in Italian, site itself is English. "ABPindo" causes the detection with the following generic rule:
~anibatch.id##.adsbox

**Comment by gmarcher** [comment]
why not easylist? 
~anibatch.id##.adsbox only for exception

**Comment by BlazDT** [comment]
The rule posted is only not applying the rule to anibatch.id and therefore breaking the site.
EasyList is not causing the detection, it is the filter list "ABPindo".
