### ISSUE TITLE
safelinku

### ISSUE THREAD

**Issue by KagaKouko99** [ABPindo/indonesianadblockrules#99]
https://www.megabatch.net/2019/08/ultraman-rb-movie-select-crystal-of.html
https://rawcdn.githack.com/riandiramdani/safelinku.com/dfea660cf01dddb004f50c30a69b4d2e58157e34/script.js

||githack.com/riandiramdani/safelinku.com/*/script.js
||githack.com/riandiramdani/safelinku.com/*/scriptlinku.js

**Comment by gmarcher** [comment]
update your subscriptions list
